
services:
  lldb_memory:
    image: neo4j:5.26.7-ubi9
    container_name: lldb_memory
    restart: unless-stopped
    ports:
      - "7484:7474"  # HTTP Browser
      - "7697:7687"  # Bolt protocol
    networks:
      - local_network
    volumes:
      - lldb_memory:/data           # graph store
      # - neo4j-logs:/logs          # query & debug logs
      # - neo4j-import:/var/lib/neo4j/import  # optional CSV import dir
    environment:
      - NEO4J_AUTH=neo4j/supersecret
      - NEO4J_PLUGINS='["apoc"]'       # install APOC
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      - NEO4J_dbms_security_allow__csv__import__from__file__urls=true
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  local_network:
    name: local_network
    driver: bridge

volumes:
  lldb_memory:
    name: lldb_memory
