//===-- GNUstepObjCRuntime.cpp ------------------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#include "GNUstepObjCRuntime.h"
#include "GNUstepClassDescriptor.h"
#include "formatters/GNUstepFormattersRegistry.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/DataFormatters/DataVisualization.h"
#include "lldb/DataFormatters/TypeCategory.h"
#include "lldb/Expression/UtilityFunction.h"
#include "lldb/Target/ExecutionContext.h"
#include "lldb/Target/Process.h"
#include "lldb/Utility/Stream.h"
#include "lldb/ValueObject/ValueObjectConstResult.h"
#include "llvm/Support/Error.h"
#include "GNUstepObjCRuntimeIntrospector.h"
#include "lldb/Target/ExecutionContext.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/Target.h"
#include "lldb/Target/ThreadPlanStepOut.h"
#include "lldb/Utility/StreamString.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"

using namespace lldb;
using namespace lldb_private;
using namespace lldb_private::formatters;

void GNUstepObjCRuntime::Initialize() {
  PluginManager::RegisterPlugin(
      "gnu-objc-v2", "GNUstep Objective-C V2 Runtime",
      CreateInstance, nullptr);
  
  Log *log = GetLog(LLDBLog::Process | LLDBLog::Types);
  LLDB_LOG(log, "GNUstepObjCRuntime::Initialize() called\n");
  
  // EMERGENCY DEBUG: Force output to stderr to confirm initialization
  fprintf(stderr, "*** GNUstepObjCRuntime::Initialize() called - Plugin registered ***\n");
  
  // CRITICAL FIX: Use consistent category name and ensure proper activation
  // The category name must be consistent between registration and activation
  ConstString category_name("gnustep");
  TypeCategoryImplSP category_sp;
  
  // Always try to create/get the category with consistent name
  if (!DataVisualization::Categories::GetCategory(category_name, category_sp) || !category_sp) {
    // Create the category if it doesn't exist
    DataVisualization::Categories::Add(category_name);
    DataVisualization::Categories::GetCategory(category_name, category_sp);
  }
  
  if (category_sp) {
    // Register formatters
    GNUstepFormattersRegistry::RegisterFormatters(*category_sp);
    
    // CRITICAL: Enable the category with both methods for maximum compatibility
    DataVisualization::Categories::Enable(category_sp, TypeCategoryMap::Default);
    DataVisualization::Categories::Enable(category_name, TypeCategoryMap::Default);
    
    LLDB_LOG(log, "GNUstepObjCRuntime: Formatters registered in category '%s' and enabled", 
             category_name.GetCString());
  } else {
    LLDB_LOG(log, "GNUstepObjCRuntime: CRITICAL ERROR - Failed to create/get category '%s'", 
             category_name.GetCString());
  }
}

void GNUstepObjCRuntime::Terminate() {
  PluginManager::UnregisterPlugin(CreateInstance);
}

// Plugin registration functions are automatically generated by LLDB_PLUGIN_DEFINE macro

LanguageRuntime *
GNUstepObjCRuntime::CreateInstance(Process *process,
                                     lldb::LanguageType language) {
  Log *log = GetLog(LLDBLog::Process | LLDBLog::Types);
  LLDB_LOG(log, "GNUstepObjCRuntime::CreateInstance() called for language {0}", language);
  
  // EMERGENCY DEBUG: Force output to stderr to confirm this is being called
  fprintf(stderr, "*** GNUstepObjCRuntime::CreateInstance() called for language %d ***\n", (int)language);
  
  if (language != eLanguageTypeObjC && language != eLanguageTypeObjC_plus_plus) {
    return nullptr;
  }
  
  if (!process) {
    return nullptr;
  }

  // First check if GNUstep runtime libraries are already loaded
  // This happens when attaching to a running process
  Target &target = process->GetTarget();
  ModuleList &modules = target.GetImages();
  
  bool found_gnustep_runtime = false;
  
  // Check for GNUstep runtime libraries
  for (size_t i = 0; i < modules.GetSize(); ++i) {
    ModuleSP module_sp = modules.GetModuleAtIndex(i);
    if (module_sp) {
      const char *module_name = module_sp->GetFileSpec().GetFilename().GetCString();
      if (module_name && 
          (strstr(module_name, "libobjc.so") || 
           strstr(module_name, "libgnustep-base.so") ||
           strstr(module_name, "libobjc2"))) {
        found_gnustep_runtime = true;
        LLDB_LOG(log, "GNUstepObjCRuntime: Found GNUstep runtime module: {0}", module_name);
        break;
      }
    }
  }
  
  if (found_gnustep_runtime) {
    LLDB_LOG(log, "GNUstepObjCRuntime: Creating instance for GNUstep runtime (libraries already loaded)");
    return new GNUstepObjCRuntime(process);
  }
  
  // If libraries aren't loaded yet, check if the main executable has Objective-C code
  // This is needed when launching a process (libraries haven't loaded yet)
  ModuleSP exe_module_sp = target.GetExecutableModule();
  if (exe_module_sp) {
    // Check for Objective-C symbols in the executable
    // GNUstep compiled code will have .objc_ symbols
    SymbolFile *sym_file = exe_module_sp->GetSymbolFile();
    if (sym_file) {
      // Simple heuristic: check for .objc_ symbols which indicate GNUstep ObjC code
      Symtab *symtab = exe_module_sp->GetSymtab();
      if (symtab) {
        const size_t num_symbols = symtab->GetNumSymbols();
        for (size_t i = 0; i < num_symbols && i < 100; ++i) { // Check first 100 symbols for efficiency
          Symbol *symbol = symtab->SymbolAtIndex(i);
          if (symbol) {
            const char *name = symbol->GetName().GetCString();
            if (name && strstr(name, ".objc_")) {
              LLDB_LOG(log, "GNUstepObjCRuntime: Found .objc_ symbol '{0}' in executable, assuming GNUstep", name);
              return new GNUstepObjCRuntime(process);
            }
          }
        }
      }
    }
  }
  
  LLDB_LOG(log, "GNUstepObjCRuntime: No GNUstep runtime or Objective-C symbols found");
  return nullptr;
}

GNUstepObjCRuntime::GNUstepObjCRuntime(Process *process)
    : ObjCLanguageRuntime(process), m_formatters_registered(false), m_gnustep_library_loaded(false) {
  Log *log = GetLog(LLDBLog::Process | LLDBLog::Types);
  LLDB_LOG(log, "GNUstepObjCRuntime constructor called");
  if (process) {
    m_introspector_up = std::make_unique<GNUstepObjCRuntimeIntrospector>(process);
    // Runtime API will be initialized when libraries are loaded
  }
  
  // Don't register formatters here - wait until we confirm GNUstep libraries are loaded
  // This will happen in ModulesDidLoad
}

GNUstepObjCRuntime::~GNUstepObjCRuntime() {
  // Note: We don't unregister formatters here as they may be used by other GNUstep processes
}

llvm::Error GNUstepObjCRuntime::GetObjectDescription(Stream &str,
                                                ValueObject &object) {
  Log *log = GetLog(LLDBLog::Process | LLDBLog::Types);
  LLDB_LOG(log, "GNUstepObjCRuntime::GetObjectDescription called");
  
  CompilerType compiler_type(object.GetCompilerType());
  bool is_signed;
  // ObjC objects can only be pointers (or numbers that actually represent
  // pointers but haven't been typecast, because reasons..)
  if (!compiler_type.IsIntegerType(is_signed) && !compiler_type.IsPointerType())
    return llvm::createStringError(llvm::inconvertibleErrorCode(), "not a pointer type");

  // Make the argument list: we pass one arg, the address of our pointer, to
  // the print function.
  Value val;

  if (!object.ResolveValue(val.GetScalar()))
    return llvm::createStringError(llvm::inconvertibleErrorCode(), "pointer value could not be resolved");

  ExecutionContext exe_ctx(object.GetExecutionContextRef());
  if (!exe_ctx.HasProcessScope()) {
    exe_ctx.SetContext(object.GetTargetSP(), true);
    if (!exe_ctx.HasProcessScope())
      return llvm::createStringError(llvm::inconvertibleErrorCode(), "no process");
  }
  
  return GetObjectDescription(str, val, exe_ctx.GetBestExecutionContextScope());
}

llvm::Error GNUstepObjCRuntime::GetObjectDescription(
    Stream &str, Value &value, ExecutionContextScope *exe_scope) {
  Log *log = GetLog(LLDBLog::Process | LLDBLog::Types);
  LLDB_LOG(log, "GNUstepObjCRuntime::GetObjectDescription(Value&) called");
  
  if (!exe_scope)
    return llvm::createStringError(llvm::inconvertibleErrorCode(), "no execution context scope");
    
  if (value.GetValueType() != Value::ValueType::Scalar)
    return llvm::createStringError(llvm::inconvertibleErrorCode(), "Value is not scalar");

  ExecutionContext exe_ctx;
  exe_scope->CalculateExecutionContext(exe_ctx);
  Process *process = exe_ctx.GetProcessPtr();
  if (!process)
    return llvm::createStringError(llvm::inconvertibleErrorCode(), "no process");

  Target *target = exe_ctx.GetTargetPtr();
  if (!target)
    return llvm::createStringError(llvm::inconvertibleErrorCode(), "no target");

  // We need other parts of the exe_ctx, but the processes have to match.
  assert(m_process == process);

  // Get the object pointer value
  lldb::addr_t object_ptr = value.GetScalar().ULongLong(LLDB_INVALID_ADDRESS);
  if (object_ptr == 0 || object_ptr == LLDB_INVALID_ADDRESS) {
    str.Printf("nil");
    return llvm::Error::success();
  }

  LLDB_LOG(log, "GNUstepObjCRuntime: Attempting to get description for object at 0x{0:x}", object_ptr);

  // Basic validation using introspector if available
  if (m_introspector_up && !m_introspector_up->IsValidObjectPointer(object_ptr)) {
    LLDB_LOG(log, "GNUstepObjCRuntime: Object pointer 0x{0:x} failed validation", object_ptr);
    return llvm::createStringError(llvm::inconvertibleErrorCode(), "invalid object pointer");
  }

  // Prepare the execution context
  if (!exe_ctx.GetFramePtr()) {
    Thread *thread = exe_ctx.GetThreadPtr();
    if (thread == nullptr) {
      exe_ctx.SetThreadSP(process->GetThreadList().GetSelectedThread());
      thread = exe_ctx.GetThreadPtr();
    }
    if (thread) {
      exe_ctx.SetFrameSP(thread->GetSelectedFrame(DoNoSelectMostRelevantFrame));
    }
  }

  // Progressive restoration of expression evaluation with proper error handling and timeouts
  LLDB_LOG(log, "GNUstepObjCRuntime: Attempting safe expression evaluation with timeouts");

  // Try expression evaluation first - it's more reliable than introspector for regular objects
  std::string class_name;

  // Try expression evaluation for -description method with safety measures
  if (exe_ctx.GetFramePtr()) {
    EvaluateExpressionOptions options;
    options.SetUnwindOnError(true);
    options.SetIgnoreBreakpoints(true);
    options.SetTryAllThreads(false); // Only current thread for safety
    options.SetTimeout(std::chrono::milliseconds(1000)); // Short 1-second timeout
    options.SetSuppressPersistentResult(true);
    options.SetKeepInMemory(false);
    options.SetUseDynamic(lldb::eDynamicCanRunTarget);

    // Try calling -description method - cast to NSString* to help LLDB resolve method signature
    char expr[256];
    snprintf(expr, sizeof(expr), "(NSString*)[(id)0x%" PRIx64 " description]", object_ptr);
    
    ValueObjectSP result_sp;
    ExpressionResults expr_result = target->EvaluateExpression(
        expr, exe_ctx.GetFramePtr(), result_sp, options);
    
    if (expr_result == eExpressionCompleted && result_sp) {
      // The result is an NSString object, we need to call UTF8String on it to get the C string
      addr_t nsstring_addr = result_sp->GetValueAsUnsigned(0);
      if (nsstring_addr != 0 && nsstring_addr != LLDB_INVALID_ADDRESS) {
        // Call UTF8String method on the NSString to get char*
        char utf8_expr[256];
        snprintf(utf8_expr, sizeof(utf8_expr), "(char*)[(id)0x%" PRIx64 " UTF8String]", nsstring_addr);
        
        ValueObjectSP utf8_result_sp;
        ExpressionResults utf8_expr_result = target->EvaluateExpression(
            utf8_expr, exe_ctx.GetFramePtr(), utf8_result_sp, options);
        
        if (utf8_expr_result == eExpressionCompleted && utf8_result_sp) {
          addr_t cstring_addr = utf8_result_sp->GetValueAsUnsigned(0);
          if (cstring_addr != 0 && cstring_addr != LLDB_INVALID_ADDRESS) {
            // Read the C string
            Status read_error;
            char desc_buffer[1024];
            size_t bytes_read = process->ReadCStringFromMemory(cstring_addr, desc_buffer, sizeof(desc_buffer), read_error);
            
            if (read_error.Success() && bytes_read > 0) {
              str.Printf("%s", desc_buffer);
              LLDB_LOG(log, "GNUstepObjCRuntime: Successfully got description via expression evaluation: {0}", desc_buffer);
              return llvm::Error::success();
            }
          }
        }
        LLDB_LOG(log, "GNUstepObjCRuntime: Failed to get UTF8String from description NSString");
      }
    } else {
      LLDB_LOG(log, "GNUstepObjCRuntime: Expression evaluation failed or timed out: result={0}", (int)expr_result);
    }
  }

  // Fallback: try to get class name using introspector
  if (m_introspector_up) {
    class_name = m_introspector_up->GetClassName(object_ptr);
    if (!class_name.empty()) {
      str.Printf("(%s *) 0x%" PRIx64, class_name.c_str(), object_ptr);
      LLDB_LOG(log, "GNUstepObjCRuntime: Using introspector class name fallback: {0}", class_name);
      return llvm::Error::success();
    }
  }

  // Final safe fallback - raw address
  str.Printf("GNUstep object at 0x%" PRIx64, object_ptr);
  LLDB_LOG(log, "GNUstepObjCRuntime: Using final raw address fallback");
  
  
  return llvm::Error::success();
}

bool GNUstepObjCRuntime::GetDynamicTypeAndAddress(ValueObject &in_value,
                                                  lldb::DynamicValueType use_dynamic,
                                                  TypeAndOrName &class_type_or_name,
                                                  Address &address,
                                                  Value::ValueType &value_type) {
  Log *log = GetLog(LLDBLog::Process | LLDBLog::Types);
  LLDB_LOG(log, "GNUstepObjCRuntime::GetDynamicTypeAndAddress called");
  
  if (!m_introspector_up) {
    LLDB_LOG(log, "No introspector available");
    return false;
  }
  
  // Get the object address first to check for tagged pointers
  lldb::addr_t object_addr = in_value.GetPointerValue();
  if (object_addr == 0 || object_addr == LLDB_INVALID_ADDRESS) {
    LLDB_LOG(log, "Invalid object address");
    return false;
  }
  
  // Check if this is a tagged pointer - they need special handling
  std::string class_name;
  if (m_introspector_up->IsTaggedPointer(object_addr)) {
    // For tagged pointers, get the class name directly using runtime functions
    class_name = m_introspector_up->GetTaggedPointerClassName(object_addr);
    LLDB_LOG(log, "Tagged pointer detected, class: {0}", class_name);
  } else {
    // For regular objects, use normal ISA resolution
    class_name = m_introspector_up->GetClassNameFromObject(in_value);
  }
  
  if (class_name.empty()) {
    LLDB_LOG(log, "Could not get class name from object");
    return false;
  }
  
  LLDB_LOG(log, "Got dynamic class name: {0}", class_name);
  
  // Set the class name in the result
  class_type_or_name.SetName(ConstString(class_name));
  
  // object_addr is already defined above, no need to redeclare
  if (object_addr == LLDB_INVALID_ADDRESS || object_addr == 0) {
    LLDB_LOG(log, "Invalid object address");
    return false;
  }
  
  // Set the address
  address.SetRawAddress(object_addr);
  value_type = Value::ValueType::LoadAddress;
  
  LLDB_LOG(log, "Dynamic type resolved: {0} at 0x{1:x}", class_name, object_addr);
  return true;
}

TypeAndOrName GNUstepObjCRuntime::FixUpDynamicType(const TypeAndOrName &type_and_or_name,
                                                   ValueObject &static_value) {
  Log *log = GetLog(LLDBLog::Process | LLDBLog::Types);
  LLDB_LOG(log, "GNUstepObjCRuntime::FixUpDynamicType called");
  
  if (!m_introspector_up) {
    LLDB_LOG(log, "No introspector available for FixUpDynamicType");
    return type_and_or_name;
  }
  
  // If we already have a class name from dynamic typing, use it
  if (type_and_or_name.HasName()) {
    return type_and_or_name;
  }
  
  // Try to get the dynamic class name
  std::string class_name = m_introspector_up->GetClassNameFromObject(static_value);
  if (!class_name.empty()) {
    LLDB_LOG(log, "FixUpDynamicType resolved to: {0}", class_name);
    TypeAndOrName result(type_and_or_name);
    result.SetName(ConstString(class_name));
    return result;
  }
  
  return type_and_or_name;
}

bool GNUstepObjCRuntime::CouldHaveDynamicValue(ValueObject &in_value) {
  Log *log = GetLog(LLDBLog::Process | LLDBLog::Types);
  LLDB_LOG(log, "GNUstepObjCRuntime::CouldHaveDynamicValue called");
  
  // Check if this is a valid object pointer
  lldb::addr_t obj_addr = in_value.GetPointerValue();
  if (obj_addr == 0 || obj_addr == LLDB_INVALID_ADDRESS) {
    LLDB_LOG(log, "Invalid object address, no dynamic value possible");
    return false;
  }
  
  // Check the static type - should be an Objective-C object pointer
  CompilerType static_type = in_value.GetCompilerType();
  if (static_type.IsValid()) {
    // Check if it's a pointer type
    if (static_type.IsPointerType()) {
      CompilerType pointee_type = static_type.GetPointeeType();
      if (pointee_type.IsValid()) {
        // Check if it looks like an Objective-C class
        std::string type_name = pointee_type.GetTypeName().GetCString();
        if (type_name.find("NS") == 0 || type_name == "id" || type_name.find("objc_object") != std::string::npos) {
          LLDB_LOG(log, "Type {0} could have dynamic value", type_name);
          return true;
        }
      }
    }
  }
  
  // If we have an introspector, check if it's a valid object
  if (m_introspector_up) {
    bool is_valid = m_introspector_up->IsValidObjectPointer(obj_addr);
    LLDB_LOG(log, "Introspector validation: {0}", is_valid ? "valid" : "invalid");
    return is_valid;
  }
  
  // Conservative default: assume it could have dynamic value
  LLDB_LOG(log, "Assuming could have dynamic value (conservative default)");
  return true;
}

lldb::BreakpointResolverSP
GNUstepObjCRuntime::CreateExceptionResolver(const lldb::BreakpointSP &bkpt, 
                                           bool catch_bp, bool throw_bp) {
  // Stub implementation
  Log *log = GetLog(LLDBLog::Process | LLDBLog::Breakpoints);
  LLDB_LOG(log, "GNUstepObjCRuntime::CreateExceptionResolver called");
  return nullptr;
}

lldb::ThreadPlanSP GNUstepObjCRuntime::GetStepThroughTrampolinePlan(Thread &thread,
                                                                    bool stop_others) {
  Log *log = GetLog(LLDBLog::Step);
  LLDB_LOG(log, "GNUstepObjCRuntime::GetStepThroughTrampolinePlan called");
  
  // Get the current thread's stack frame
  StackFrameSP frame_sp = thread.GetStackFrameAtIndex(0);
  if (!frame_sp) {
    LLDB_LOG(log, "No current stack frame available");
    return nullptr;
  }
  
  // Get the symbol context for the current frame
  // Focus on symbols since objc_msgSend functions are typically runtime symbols
  SymbolContext sc = frame_sp->GetSymbolContext(eSymbolContextSymbol);
  
  // Check if we have a symbol
  const char *symbol_name = nullptr;
  if (sc.symbol && sc.symbol->GetName()) {
    symbol_name = sc.symbol->GetName().GetCString();
  }
  
  if (!symbol_name) {
    LLDB_LOG(log, "No symbol name available for current frame");
    return nullptr;
  }
  
  LLDB_LOG(log, "Current symbol: {0}", symbol_name);
  
  // Check if this is an objc_msgSend trampoline function
  // GNUstep uses similar naming to Apple for these functions, plus some GNUstep-specific variants
  bool is_objc_trampoline = false;
  
  // Check for standard objc_msgSend variants
  if (strncmp(symbol_name, "objc_msgSend", 12) == 0) {
    // Handle various objc_msgSend variants:
    // - objc_msgSend (basic message send)
    // - objc_msgSendSuper (super calls)
    // - objc_msgSend_stret (struct returns)
    // - objc_msgSendSuper_stret (super calls with struct returns)
    is_objc_trampoline = (strcmp(symbol_name, "objc_msgSend") == 0 ||
                         strcmp(symbol_name, "objc_msgSendSuper") == 0 ||
                         strcmp(symbol_name, "objc_msgSend_stret") == 0 ||
                         strcmp(symbol_name, "objc_msgSendSuper_stret") == 0 ||
                         strcmp(symbol_name, "objc_msgSend_fpret") == 0 ||
                         strcmp(symbol_name, "objc_msgSend_fp2ret") == 0);
  }
  
  // Check for GNUstep-specific trampoline symbols  
  if (!is_objc_trampoline) {
    // GNUstep may have different symbol names for trampolines
    is_objc_trampoline = (strstr(symbol_name, "objc_block_trampoline") != nullptr ||
                         strstr(symbol_name, "objc_trampoline") != nullptr ||
                         strstr(symbol_name, "objc_msgLookup") != nullptr ||
                         strstr(symbol_name, "__objc_msg") != nullptr ||
                         (strstr(symbol_name, "objc") != nullptr && 
                          (strstr(symbol_name, "trampoline") != nullptr || 
                           strstr(symbol_name, "dispatch") != nullptr ||
                           strstr(symbol_name, "lookup") != nullptr)));
  }
  
  if (!is_objc_trampoline) {
    LLDB_LOG(log, "Not in objc_msgSend trampoline, symbol: {0}", symbol_name);
    return nullptr;
  }
  
  // Verify this symbol is from the objc runtime library, not user code
  if (sc.module_sp) {
    const char *module_name = sc.module_sp->GetFileSpec().GetFilename().GetCString();
    if (module_name) {
      bool is_objc_runtime = (strstr(module_name, "libobjc") != nullptr ||
                             strstr(module_name, "libgnustep-base") != nullptr ||
                             strstr(module_name, "libobjc2") != nullptr);
      if (!is_objc_runtime) {
        LLDB_LOG(log, "Symbol {0} is not from objc runtime library (module: {1})", 
                 symbol_name, module_name);
        return nullptr;
      }
      LLDB_LOG(log, "Confirmed objc_msgSend trampoline in runtime library: {0}", module_name);
    }
  }
  
  LLDB_LOG(log, "Detected objc_msgSend trampoline: {0}, creating step-out plan", symbol_name);
  
  // Create a ThreadPlanStepOut to step out of the trampoline
  // This will cause LLDB to step over the objc_msgSend assembly and land
  // directly in the actual method implementation
  ThreadPlanSP step_out_plan_sp = std::make_shared<ThreadPlanStepOut>(
      thread,
      &sc,                    // symbol context
      false,                  // first_insn - not first instruction  
      stop_others,            // stop_others - as requested
      eVoteNoOpinion,         // report_stop_vote - no opinion
      eVoteNoOpinion,         // report_run_vote - no opinion
      0,                      // frame_idx - step out of current frame
      eLazyBoolCalculate,     // step_out_avoids_code_without_debug_info
      false,                  // continue_to_next_branch
      false                   // gather_return_value - not needed for trampolines
  );
  
  if (step_out_plan_sp) {
    LLDB_LOG(log, "Created ThreadPlanStepOut for objc_msgSend trampoline");
  } else {
    LLDB_LOG(log, "Failed to create ThreadPlanStepOut for objc_msgSend trampoline");
  }
  
  return step_out_plan_sp;
}

bool GNUstepObjCRuntime::IsModuleObjCLibrary(const lldb::ModuleSP &module_sp) {
  if (!module_sp)
    return false;
  
  const char *module_name = module_sp->GetFileSpec().GetFilename().GetCString();
  if (!module_name)
    return false;
  
  // Check for GNUstep runtime libraries - handle versioned library names
  // Examples: libobjc.so.4.6, libgnustep-base.so.1.31, libobjc2.so.4
  return (strstr(module_name, "libobjc.so") ||         // libobjc.so.4.6
          strstr(module_name, "libgnustep-base.so") || // libgnustep-base.so.1.31  
          strstr(module_name, "libobjc2.so") ||        // libobjc2.so.4
          strstr(module_name, "libobjc2") ||           // libobjc2 (unversioned)
          strstr(module_name, "libBlocksRuntime"));    // libBlocksRuntime for blocks support
}

bool GNUstepObjCRuntime::ReadObjCLibrary(const lldb::ModuleSP &module_sp) {
  if (!IsModuleObjCLibrary(module_sp))
    return false;
  
  Log *log = GetLog(LLDBLog::Process | LLDBLog::Types);
  LLDB_LOG(log, "GNUstepObjCRuntime::ReadObjCLibrary called for module: {0}",
           module_sp->GetFileSpec().GetFilename().GetCString());
  
  m_has_read_objc_library = true;
  return true;
}

bool GNUstepObjCRuntime::HasReadObjCLibrary() {
  return m_has_read_objc_library;
}

llvm::Expected<std::unique_ptr<UtilityFunction>>
GNUstepObjCRuntime::CreateObjectChecker(std::string name, ExecutionContext &exe_ctx) {
  Log *log = GetLog(LLDBLog::Process | LLDBLog::Types);
  LLDB_LOG(log, "GNUstepObjCRuntime::CreateObjectChecker called with name: {0}", name);
  
  // Create a working object checker using GNUstep runtime functions
  // This follows Apple's pattern but uses GNUstep-specific runtime functions
  LLDB_LOG(log, "GNUstepObjCRuntime::CreateObjectChecker: Creating GNUstep runtime-based object checker");
  
  char check_function_code[2048];
  
  // Create a full-featured object checker using GNUstep runtime functions
  int len = ::snprintf(check_function_code, sizeof(check_function_code), R"(
extern "C" void *object_getClass(void *obj);
extern "C" int class_respondsToSelector(void *cls, void *sel);
extern "C" int printf(const char *format, ...);
extern "C" void
%s(void *$__lldb_arg_obj, void *$__lldb_arg_selector) {
  // nil object is always OK for Objective-C
  if ($__lldb_arg_obj == (void *)0)
    return;
  
  // Get the object's class using GNUstep runtime function
  void *objc_class = object_getClass($__lldb_arg_obj);
  if (!objc_class) {
    // Invalid object - cause controlled crash for conditional breakpoints
    // This follows Apple's pattern for LLDB integration
    *((volatile int *)0) = 'ocgc';
  } else if ($__lldb_arg_selector != (void *)0) {
    // Check if class responds to selector using GNUstep runtime
    int responds = class_respondsToSelector(objc_class, $__lldb_arg_selector);
    if (responds == 0) {
      // Object doesn't respond to selector - cause controlled crash
      *((volatile int *)0) = 'ocgc';
    }
  }
  // If we get here, validation passed - continue normally
})",
                     name.c_str());

  if (len >= (int)sizeof(check_function_code)) {
    LLDB_LOG(log, "GNUstepObjCRuntime::CreateObjectChecker: Generated code too long");
    return llvm::createStringError(llvm::inconvertibleErrorCode(), 
                                   "Object checker code generation failed - code too long");
  }

  LLDB_LOG(log, "GNUstepObjCRuntime::CreateObjectChecker: Generated GNUstep runtime-based checker code:\n{0}", 
           check_function_code);

  // Create the utility function that LLDB can execute
  return GetTargetRef().CreateUtilityFunction(check_function_code, name,
                                              eLanguageTypeC, exe_ctx);
}

void GNUstepObjCRuntime::UpdateISAToDescriptorMapIfNeeded() {
  Log *log = GetLog(LLDBLog::Process | LLDBLog::Types);
  LLDB_LOG(log, "GNUstepObjCRuntime::UpdateISAToDescriptorMapIfNeeded called");
  
  if (!m_runtime_api_up) {
    LLDB_LOG(log, "No runtime API available for ISA map update");
    return;
  }
  
  // Get all Foundation classes from the runtime
  auto foundation_classes = m_runtime_api_up->GetAllFoundationClasses();
  if (!foundation_classes) {
    // Consume the error and continue - this isn't critical
    llvm::consumeError(foundation_classes.takeError());
    LLDB_LOG(log, "Could not enumerate Foundation classes for ISA map");
    return;
  }
  
  LLDB_LOG(log, "Updating ISA map with {0} Foundation classes", 
           foundation_classes->size());
  
  // Add each class to the ISA-to-descriptor map
  for (const auto &class_info : *foundation_classes) {
    lldb::addr_t class_addr = reinterpret_cast<lldb::addr_t>(class_info.class_ptr);
    if (class_addr != LLDB_INVALID_ADDRESS && class_addr != 0) {
      // Check if we already have this ISA in our map
      ClassDescriptorSP existing_descriptor = ObjCLanguageRuntime::GetClassDescriptorFromISA(class_addr);
      if (!existing_descriptor) {
        // Create a new descriptor for this class
        ClassDescriptorSP new_descriptor = ClassDescriptorSP(
            new GNUstepClassDescriptor(*this, class_addr, class_info.name.c_str()));
        
        if (new_descriptor && new_descriptor->IsValid()) {
          AddClass(class_addr, new_descriptor);
          LLDB_LOG(log, "Added ISA mapping: 0x{0:x} -> {1}", 
                   class_addr, class_info.name);
        }
      }
    }
  }
  
  // Also update any custom classes we've encountered during runtime introspection
  if (m_introspector_up) {
    // The introspector may have cached ISA-to-name mappings we can use
    // This is a future enhancement point for custom class discovery
  }
}

ObjCLanguageRuntime::ClassDescriptorSP
GNUstepObjCRuntime::GetClassDescriptorFromISA(ObjCISA isa) {
  Log *log = GetLog(LLDBLog::Process | LLDBLog::Types);
  LLDB_LOG(log, "GNUstepObjCRuntime::GetClassDescriptorFromISA called with ISA {0:x}", isa);
  
  if (!isa)
    return ClassDescriptorSP();
  
  // First check the base class cache
  UpdateISAToDescriptorMap();
  ClassDescriptorSP descriptor_sp = ObjCLanguageRuntime::GetClassDescriptorFromISA(isa);
  if (descriptor_sp)
    return descriptor_sp;
  
  // If not in cache, create a new GNUstepClassDescriptor
  descriptor_sp = ClassDescriptorSP(new GNUstepClassDescriptor(*this, isa, nullptr));
  
  // Add to cache if valid
  if (descriptor_sp && descriptor_sp->IsValid()) {
    AddClass(isa, descriptor_sp);
    return descriptor_sp;
  }
  
  return ClassDescriptorSP();
}

ObjCLanguageRuntime::ClassDescriptorSP
GNUstepObjCRuntime::GetClassDescriptor(ValueObject &valobj) {
  Log *log = GetLog(LLDBLog::Process | LLDBLog::Types);
  LLDB_LOG(log, "GNUstepObjCRuntime::GetClassDescriptor called for ValueObject");
  
  // Handle base class case (like Apple's implementation)
  if (valobj.IsBaseClass()) {
    ValueObject *parent = valobj.GetParent();
    if (parent && parent != &valobj) {
      ClassDescriptorSP parent_descriptor_sp = GetClassDescriptor(*parent);
      if (parent_descriptor_sp)
        return parent_descriptor_sp->GetSuperclass();
    }
    return nullptr;
  }
  
  // Get the ISA pointer from the object
  addr_t isa_pointer = valobj.GetPointerValue();
  if (!isa_pointer)
    return ClassDescriptorSP();
  
  // Read the ISA from the object's first field
  ExecutionContext exe_ctx(valobj.GetExecutionContextRef());
  Process *process = exe_ctx.GetProcessPtr();
  if (!process)
    return ClassDescriptorSP();
  
  Status error;
  ObjCISA isa = process->ReadPointerFromMemory(isa_pointer, error);
  if (error.Fail())
    return ClassDescriptorSP();
  
  return GetClassDescriptorFromISA(isa);
}

void GNUstepObjCRuntime::ModulesDidLoad(const ModuleList &module_list) {
  // CRITICAL FIX: Add guards to prevent infinite recursion
  static thread_local int recursion_depth = 0;
  static thread_local bool in_modules_did_load = false;
  
  // Prevent infinite recursion
  if (in_modules_did_load || recursion_depth > 5) {
    Log *log = GetLog(LLDBLog::Process | LLDBLog::Types);
    LLDB_LOG(log, "GNUstepObjCRuntime::ModulesDidLoad - recursion detected, skipping (depth={0})", recursion_depth);
    return;
  }
  
  // Set guards
  in_modules_did_load = true;
  recursion_depth++;
  
  // Reduce debug spam - only log when we find GNUstep libraries
  Log *log = GetLog(LLDBLog::Process | LLDBLog::Types);
  LLDB_LOG(log, "GNUstepObjCRuntime::ModulesDidLoad called with {0} modules", 
           module_list.GetSize());
  
  // Call parent class method first (like Apple's implementation)
  ObjCLanguageRuntime::ModulesDidLoad(module_list);
  
  // Check if any of the newly loaded modules are GNUstep ObjC libraries
  bool found_gnustep = false;
  for (size_t i = 0; i < module_list.GetSize(); ++i) {
    ModuleSP module_sp = module_list.GetModuleAtIndex(i);
    if (IsModuleObjCLibrary(module_sp)) {
      found_gnustep = true;
      m_gnustep_library_loaded = true;
      ReadObjCLibrary(module_sp);
      LLDB_LOG(log, "GNUstepObjCRuntime: Found GNUstep library: {0}", 
               module_sp->GetFileSpec().GetFilename().GetCString());
    }
  }
  
  // Register formatters when we confirm GNUstep libraries are loaded
  if (found_gnustep) {
    if (!m_formatters_registered) {
      LLDB_LOG(log, "GNUstepObjCRuntime: GNUstep libraries detected, registering formatters");
      RegisterFormatters();
    }
    
    // Initialize the runtime API now that libraries are loaded
    if (!m_runtime_api_up) {
      InitializeRuntimeAPI();
    }
  }
  
  // Clear guards
  recursion_depth--;
  in_modules_did_load = false;
}

void GNUstepObjCRuntime::InitializeRuntimeAPI() {
  Log *log = GetLog(LLDBLog::Process | LLDBLog::Types);
  LLDB_LOG(log, "GNUstepObjCRuntime::InitializeRuntimeAPI - Initializing runtime API");
  
  if (!m_process) {
    LLDB_LOG(log, "No process available for runtime API");
    return;
  }
  
  auto api_or_error = GNUstepRuntimeV2API::Create(m_process);
  if (api_or_error) {
    m_runtime_api_up = std::move(*api_or_error);
    LLDB_LOG(log, "Runtime V2 API initialized successfully");
    
    // Log runtime version
    if (m_runtime_api_up) {
      std::string version = m_runtime_api_up->GetRuntimeVersion();
      LLDB_LOG(log, "Runtime version: {0}", version);
      
      // Enumerate and log Foundation classes
      auto foundation_classes = m_runtime_api_up->GetAllFoundationClasses();
      if (foundation_classes) {
        LLDB_LOG(log, "Found {0} Foundation classes", foundation_classes->size());
        
        // Log first few Foundation classes for debugging
        size_t count = 0;
        for (const auto &cls : *foundation_classes) {
          if (count++ < 10) {
            LLDB_LOG(log, "  Foundation class: {0} (superclass: {1})", 
                     cls.name, cls.superclass_name);
          }
        }
      } else {
        // Consume the error from GetAllFoundationClasses
        llvm::consumeError(foundation_classes.takeError());
        // This is not critical - formatters will still work through other mechanisms
        LLDB_LOG(log, "[GNUstepObjC] Note: Runtime class enumeration not available, using fallback mechanisms");
      }
    }
  } else {
    llvm::handleAllErrors(api_or_error.takeError(),
                          [&](const llvm::StringError &SE) {
                            LLDB_LOG(log, "Failed to initialize runtime API: {0}", 
                                     SE.getMessage());
                          });
  }
}

void GNUstepObjCRuntime::RegisterFormatters() {
  if (m_formatters_registered) {
    return;
  }
    
  Log *log = GetLog(LLDBLog::Process | LLDBLog::Types);
  LLDB_LOG(log, "GNUstepObjCRuntime::RegisterFormatters - Registering GNUstep formatters");
  
  // Disable Apple's ObjC formatters to prevent conflicts
  // This is necessary because both Apple and GNUstep register formatters for the same types
  TypeCategoryImplSP objc_category_sp;
  if (DataVisualization::Categories::GetCategory(ConstString("objc"), objc_category_sp)) {
    DataVisualization::Categories::Disable(ConstString("objc"));
    LLDB_LOG(log, "Disabled Apple ObjC formatters to prevent conflicts");
  }
  
  // Get or create the GNUstep type category
  TypeCategoryImplSP category_sp;
  if (!DataVisualization::Categories::GetCategory(ConstString("gnustep"), 
                                                  category_sp, true)) {
    LLDB_LOG(log, "Failed to get/create GNUstep category");
    return;
  }
  
  if (!category_sp) {
    LLDB_LOG(log, "Got null category pointer");
    return;
  }
  
  // Register our formatters
  GNUstepFormattersRegistry::RegisterFormatters(*category_sp);
  
  // Enable the category with higher priority than default
  DataVisualization::Categories::Enable(ConstString("gnustep"), 
                                        TypeCategoryMap::Default);
  
  m_formatters_registered = true;
  LLDB_LOG(log, "GNUstep formatters registered and category enabled");
}

DeclVendor *GNUstepObjCRuntime::GetDeclVendor() {
  if (!m_decl_vendor_up) {
    m_decl_vendor_up = std::make_unique<GNUstepObjCDeclVendor>(*this);
  }
  
  return m_decl_vendor_up.get();
}

LLDB_PLUGIN_DEFINE(GNUstepObjCRuntime)
