//===-- GNUstepObjCRuntime.cpp ------------------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#include "GNUstepObjCRuntime.h"
#include "GNUstepObjCRuntimeUtilities.h"
#include "formatters/GNUstepUniversalFormatter.h"
#include "lldb/Core/PluginManager.h"
#include "lldb/Expression/UtilityFunction.h"
#include "lldb/Expression/DiagnosticManager.h"
#include "lldb/Target/ExecutionContext.h"
#include "lldb/Target/Process.h"
#include "lldb/Utility/Stream.h"
#include "lldb/Utility/StreamString.h"
#include "lldb/ValueObject/ValueObjectConstResult.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/SaveAndRestore.h"
#include "GNUstepObjCRuntimeIntrospector.h"
#include "lldb/Target/ExecutionContext.h"
#include "lldb/Target/Process.h"
#include "lldb/Target/Target.h"
#include "lldb/Target/ThreadPlanStepOut.h"
#include "lldb/Target/ThreadPlanCallFunction.h"
#include "lldb/Target/Thread.h"
#include "lldb/Core/Address.h"
#include "lldb/Core/Value.h"
#include "lldb/ValueObject/ValueObjectList.h"
#include "lldb/Utility/StreamString.h"
#include "lldb/Utility/LLDBLog.h"
#include "lldb/Utility/Log.h"
#include "lldb/Expression/DiagnosticManager.h"
#include "Plugins/TypeSystem/Clang/TypeSystemClang.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/Decl.h"
#include <atomic>

using namespace lldb;
using namespace lldb_private;
using namespace lldb_private::formatters;
using namespace lldb_private::gnustep_objc_runtime_utilities;

void GNUstepObjCRuntime::Initialize() {
  PluginManager::RegisterPlugin(
      "gnu-objc-v2", "GNUstep Objective-C V2 Runtime",
      CreateInstance, nullptr);
}

void GNUstepObjCRuntime::Terminate() {
  PluginManager::UnregisterPlugin(CreateInstance);
}

// Plugin registration functions are automatically generated by LLDB_PLUGIN_DEFINE macro

LanguageRuntime *
GNUstepObjCRuntime::CreateInstance(Process *process,
                                     lldb::LanguageType language) {
  // We handle ObjC, ObjC++, and C since GNUstep projects often mix C and ObjC code
  // Note: C support requires relaxed assertion in Process.cpp
  if (language != eLanguageTypeObjC && 
      language != eLanguageTypeObjC_plus_plus && 
      language != eLanguageTypeC) {
    return nullptr;
  }

  // Quick ObjC marker check - look for key sections/symbols
  ModuleSP exe_module = process->GetTarget().GetExecutableModule();
  if (!exe_module)
    return nullptr;
    
  bool found_objc_markers = false;
  
  // Check for ObjC sections first (most reliable)
  if (SectionList *sections = exe_module->GetSectionList()) {
    for (size_t i = 0; i < sections->GetSize() && !found_objc_markers; ++i) {
      if (SectionSP section = sections->GetSectionAtIndex(i)) {
        if (ConstString name = section->GetName()) {
          const char *section_name = name.GetCString();
          if (strstr(section_name, ".objc") || strstr(section_name, "__objc_")) {
            found_objc_markers = true;
          }
        }
      }
    }
  }
  
  // Fallback: check for core runtime symbols
  if (!found_objc_markers) {
    if (Symtab *symtab = exe_module->GetSymtab()) {
      const char* core_symbols[] = {"objc_msgSend", "_objc_", ".objc_", nullptr};
      for (int i = 0; core_symbols[i] && !found_objc_markers; i++) {
        std::vector<uint32_t> matches;
        symtab->FindAllSymbolsWithNameAndType(ConstString(core_symbols[i]), eSymbolTypeAny, matches);
        found_objc_markers = !matches.empty();
      }
    }
  }
  
  if (!found_objc_markers) {
    printf("[DEBUG] No ObjC markers found, returning nullptr\n");
    return nullptr;
  }
  
  printf("[DEBUG] ObjC markers found, creating GNUstepObjCRuntime\n");
  std::unique_ptr<GNUstepObjCRuntime> runtime_sp(new GNUstepObjCRuntime(process));
  // Don't install hooks here - let them be installed after process launch
  return runtime_sp.release();
}

GNUstepObjCRuntime::GNUstepObjCRuntime(Process *process)
    : ObjCLanguageRuntime(process), m_gnustep_library_loaded(false) {
  // Initialize the consolidated runtime function caller
  if (process) {
    m_runtime_caller = std::make_unique<RuntimeFunctionCaller>(process);
  }
  
  // Initialize the introspector for object introspection
  m_introspector_up = std::make_unique<GNUstepObjCRuntimeIntrospector>(process);
  // Defer all heavy initialization to ModulesDidLoad
}

GNUstepObjCRuntime::~GNUstepObjCRuntime() {
}

void GNUstepObjCRuntime::ArmEarlyInstall() {
  if (!m_expression_hooks_installed) {
    ResolveAndCacheRuntimeSymbols();
    if (m_objc_msgSend_addr != LLDB_INVALID_ADDRESS ||
        m_objc_getClass_addr != LLDB_INVALID_ADDRESS) {
      m_gnustep_library_loaded = true;
      InstallExpressionEvaluationHooks();
    }
  }
}

void GNUstepObjCRuntime::ModulesDidLoad(const ModuleList &module_list) {
  // Invalidate object description cache when modules load
  m_object_description_cache.descriptions.clear();
  m_object_description_cache.last_invalidation = std::chrono::steady_clock::now();
  
  if (m_expression_hooks_installed)
    return;
  
  // Check for libobjc2 modules
  bool found_objc_module = false;
  for (size_t i = 0; i < module_list.GetSize(); ++i) {
    ModuleSP module_sp = module_list.GetModuleAtIndex(i);
    if (!module_sp) continue;
    
    const char *module_name = module_sp->GetFileSpec().GetFilename().GetCString();
    if (module_name && (strstr(module_name, "libobjc") || strstr(module_name, "objc2") ||
        (strstr(module_name, "objc") && strstr(module_name, ".dll")))) {
      found_objc_module = true;
      m_gnustep_library_loaded = true;
      break;
    }
  }
  
  if (found_objc_module) {
    ResolveAndCacheRuntimeSymbols();
    if (m_objc_msgSend_addr != LLDB_INVALID_ADDRESS ||
        m_objc_getClass_addr != LLDB_INVALID_ADDRESS) {
      InstallExpressionEvaluationHooks();
    }
  }
}

void GNUstepObjCRuntime::DidLaunch() {
  Log *log = GetLog(LLDBLog::Language | LLDBLog::Types);
  LLDB_LOG(log, "[GNUstep] DidLaunch: Process launched, registering formatters only");
  printf("[DEBUG] GNUstepObjCRuntime::DidLaunch called\n");
  
  // Formatters are registered in ObjCLanguage.cpp via LoadGNUstepFormatters()
  // Expression evaluation hooks will be installed lazily when needed
  // This prevents hanging with NSNumber literals during process launch
}

void GNUstepObjCRuntime::DidAttach(ArchSpec &arch_spec) {
  Log *log = GetLog(LLDBLog::Language | LLDBLog::Types);
  LLDB_LOG(log, "[GNUstep] DidAttach: Process attached, registering formatters only");
  
  // Formatters are registered in ObjCLanguage.cpp via LoadGNUstepFormatters()
  // Expression evaluation hooks will be installed lazily when needed
  // This prevents hanging with NSNumber literals during process attach
}

llvm::Error GNUstepObjCRuntime::GetObjectDescription(Stream &str,
                                                ValueObject &object) {
  Log *log = GetLog(LLDBLog::Process | LLDBLog::Types);
  LLDB_LOG(log, "GNUstepObjCRuntime::GetObjectDescription called");
  
  CompilerType compiler_type(object.GetCompilerType());
  bool is_signed;
  // ObjC objects can only be pointers (or numbers that actually represent
  // pointers but haven't been typecast, because reasons..)
  if (!compiler_type.IsIntegerType(is_signed) && !compiler_type.IsPointerType())
    return llvm::createStringError(llvm::inconvertibleErrorCode(), "not a pointer type");

  // Make the argument list: we pass one arg, the address of our pointer, to
  // the print function.
  Value val;

  if (!object.ResolveValue(val.GetScalar()))
    return llvm::createStringError(llvm::inconvertibleErrorCode(), "pointer value could not be resolved");

  ExecutionContext exe_ctx(object.GetExecutionContextRef());
  if (!exe_ctx.HasProcessScope()) {
    exe_ctx.SetContext(object.GetTargetSP(), true);
    if (!exe_ctx.HasProcessScope())
      return llvm::createStringError(llvm::inconvertibleErrorCode(), "no process");
  }
  
  return GetObjectDescription(str, val, exe_ctx.GetBestExecutionContextScope());
}

llvm::Error GNUstepObjCRuntime::GetObjectDescription(
    Stream &str, Value &value, ExecutionContextScope *exe_scope) {
  Log *log = GetLog(LLDBLog::Process | LLDBLog::Types);
  LLDB_LOG(log, "GNUstepObjCRuntime::GetObjectDescription(Value&) called");
  
  // Add reentrancy guard to prevent recursive calls
  SimpleReentrancyGuard guard(m_in_object_description);
  if (!guard.IsAcquired()) {
    LLDB_LOG(log, "GNUstepObjCRuntime: Reentrancy detected in GetObjectDescription, returning minimal info");
    str.Printf("<object description recursion detected>");
    return llvm::Error::success();
  }
  
  if (!exe_scope)
    return llvm::createStringError(llvm::inconvertibleErrorCode(), "no execution context scope");
    
  if (value.GetValueType() != Value::ValueType::Scalar)
    return llvm::createStringError(llvm::inconvertibleErrorCode(), "Value is not scalar");

  ExecutionContext exe_ctx;
  exe_scope->CalculateExecutionContext(exe_ctx);
  Process *process = exe_ctx.GetProcessPtr();
  if (!process)
    return llvm::createStringError(llvm::inconvertibleErrorCode(), "no process");

  Target *target = exe_ctx.GetTargetPtr();
  if (!target)
    return llvm::createStringError(llvm::inconvertibleErrorCode(), "no target");

  // We need other parts of the exe_ctx, but the processes have to match.
  assert(m_process == process);

  // Get the object pointer value
  lldb::addr_t object_ptr = value.GetScalar().ULongLong(LLDB_INVALID_ADDRESS);
  if (object_ptr == 0 || object_ptr == LLDB_INVALID_ADDRESS) {
    str.Printf("nil");
    return llvm::Error::success();
  }

  // Check cache first
  m_object_description_cache.InvalidateIfStale();
  auto cache_it = m_object_description_cache.descriptions.find(object_ptr);
  if (cache_it != m_object_description_cache.descriptions.end()) {
    LLDB_LOG(log, "GNUstepObjCRuntime: Found cached description for 0x{0:x}: {1}", object_ptr, cache_it->second);
    str.Printf("%s", cache_it->second.c_str());
    return llvm::Error::success();
  }

  LLDB_LOG(log, "GNUstepObjCRuntime: Attempting to get description for object at 0x{0:x}", object_ptr);

  // Handle tagged pointers BEFORE expression evaluation
  // Tagged pointers are immediate values that cannot be handled by expression evaluation
  if (m_introspector_up && m_introspector_up->IsTaggedPointer(object_ptr)) {
    LLDB_LOG(log, "GNUstepObjCRuntime: Object 0x{0:x} is a tagged pointer", object_ptr);
    
    // For tagged strings, decode directly using introspector
    uint64_t tag = object_ptr & 0x7;
    if (tag == 4) { // GSTinyString tag
      std::string decoded_string = m_introspector_up->DecodeTaggedString(object_ptr);
      if (!decoded_string.empty()) {
        str.Printf("%s", decoded_string.c_str());
        LLDB_LOG(log, "GNUstepObjCRuntime: Decoded tagged string: {0}", decoded_string);
        
        // Cache the description
        m_object_description_cache.descriptions[object_ptr] = decoded_string;
        
        return llvm::Error::success();
      }
    } else if (tag == 1 || tag == 3) { // Tagged numbers
      // Decode tagged number
      if (tag == 1) { // NSSmallInt
        int64_t int_value = ((int64_t)object_ptr) >> 3;
        str.Printf("%" PRId64, int_value);
        LLDB_LOG(log, "GNUstepObjCRuntime: Decoded tagged int: {0}", int_value);
        
        // Cache the description
        std::string int_desc = std::to_string(int_value);
        m_object_description_cache.descriptions[object_ptr] = int_desc;
        
        return llvm::Error::success();
      }
    }
    
    // For other tagged pointer types, use class name fallback
    std::string tag_class_name = m_introspector_up->GetTaggedPointerClassName(object_ptr);
    if (!tag_class_name.empty()) {
      str.Printf("<%s tagged pointer: 0x%llx>", tag_class_name.c_str(), (unsigned long long)object_ptr);
      LLDB_LOG(log, "GNUstepObjCRuntime: Tagged pointer class name: {0}", tag_class_name);
      
      // Cache the description
      std::string tag_desc = llvm::formatv("<{0} tagged pointer: 0x{1:x}>", tag_class_name, object_ptr);
      m_object_description_cache.descriptions[object_ptr] = tag_desc;
      
      return llvm::Error::success();
    }
  }

  // Basic validation using introspector if available (for regular objects only)
  if (m_introspector_up && !m_introspector_up->IsTaggedPointer(object_ptr) && 
      !m_introspector_up->IsValidObjectPointer(object_ptr)) {
    LLDB_LOG(log, "GNUstepObjCRuntime: Object pointer 0x{0:x} failed validation", object_ptr);
    return llvm::createStringError(llvm::inconvertibleErrorCode(), "invalid object pointer");
  }

  // Prepare the execution context
  if (!exe_ctx.GetFramePtr()) {
    Thread *thread = exe_ctx.GetThreadPtr();
    if (thread == nullptr) {
      exe_ctx.SetThreadSP(process->GetThreadList().GetSelectedThread());
      thread = exe_ctx.GetThreadPtr();
    }
    if (thread) {
      exe_ctx.SetFrameSP(thread->GetSelectedFrame(DoNoSelectMostRelevantFrame));
    }
  }

  // Progressive restoration of expression evaluation with proper error handling and timeouts
  LLDB_LOG(log, "GNUstepObjCRuntime: Attempting safe description call with FunctionCaller approach");

  // Try using FunctionCaller for objc_msgSend instead of expression evaluation
  std::string class_name;

  // TODO: Replace with FunctionCaller-based objc_msgSend call for -description method
  // This is more complex than C function calls because it requires:
  // 1. Setting up objc_msgSend with proper calling convention
  // 2. Resolving the -description selector
  // 3. Handling the returned NSString object
  // 4. Calling -UTF8String on the NSString
  // For now, keeping the expression evaluation as a transitional approach
  // but documenting the intention to replace with FunctionCaller
  
  if (exe_ctx.GetFramePtr()) {
    // Try simple expression evaluation
    EvaluateExpressionOptions options = MakeSafeExpressionOptions();
    options.SetSuppressPersistentResult(true);
    options.SetKeepInMemory(false);
    options.SetUseDynamic(lldb::eDynamicCanRunTarget);

    // Try calling -description method - cast to NSString* to help LLDB resolve method signature
    char expr[256];
    snprintf(expr, sizeof(expr), "(NSString*)[(id)0x%" PRIx64 " description]", object_ptr);
    
    // DEBUG: Log what we're trying to evaluate
    LLDB_LOG(log, "GNUstepObjCRuntime: About to evaluate expression: {0}", expr);
    
    ValueObjectSP result_sp;
    ExpressionResults expr_result = target->EvaluateExpression(
        expr, exe_ctx.GetFramePtr(), result_sp, options);
    
    LLDB_LOG(log, "GNUstepObjCRuntime: Expression result: {0}, result_sp: {1}", 
             (int)expr_result, (result_sp ? "valid" : "null"));
    
    if (expr_result == eExpressionCompleted && result_sp) {
      // The result is an NSString object, we need to call UTF8String on it to get the C string
      addr_t nsstring_addr = result_sp->GetValueAsUnsigned(0);
      if (nsstring_addr != 0 && nsstring_addr != LLDB_INVALID_ADDRESS) {
        // Use expression evaluation for UTF8String
        char utf8_expr[256];
        snprintf(utf8_expr, sizeof(utf8_expr), "(char*)[(id)0x%" PRIx64 " UTF8String]", nsstring_addr);
        
        ValueObjectSP utf8_result_sp;
        ExpressionResults utf8_expr_result = target->EvaluateExpression(
            utf8_expr, exe_ctx.GetFramePtr(), utf8_result_sp, options);
        
        if (utf8_expr_result == eExpressionCompleted && utf8_result_sp) {
          addr_t cstring_addr = utf8_result_sp->GetValueAsUnsigned(0);
          if (cstring_addr != 0 && cstring_addr != LLDB_INVALID_ADDRESS) {
            // Read the C string
            Status read_error;
            char desc_buffer[1024];
            size_t bytes_read = process->ReadCStringFromMemory(cstring_addr, desc_buffer, sizeof(desc_buffer), read_error);
            
            if (read_error.Success() && bytes_read > 0) {
              str.Printf("%s", desc_buffer);
              LLDB_LOG(log, "GNUstepObjCRuntime: Successfully got description via expression evaluation: {0}", desc_buffer);
              
              // Cache the description
              m_object_description_cache.descriptions[object_ptr] = std::string(desc_buffer);
              
              return llvm::Error::success();
            }
          }
        }
        LLDB_LOG(log, "GNUstepObjCRuntime: Failed to get UTF8String from description NSString");
      }
    } else {
      LLDB_LOG(log, "GNUstepObjCRuntime: Expression evaluation failed or timed out: result={0}", (int)expr_result);
    }
  }

  // Try to use our ID dispatcher as a fallback
  // This makes po commands work by using our formatter dispatch system
  LLDB_LOG(log, "GNUstepObjCRuntime: Expression evaluation failed, trying formatter dispatch fallback");
  
  // Create a temporary ValueObject to pass to our formatters
  if (exe_ctx.GetFramePtr()) {
    CompilerType void_ptr_type;
    if (TypeSystemClangSP scratch_ts_sp = 
            ScratchTypeSystemClang::GetForTarget(*target)) {
      void_ptr_type = scratch_ts_sp->GetBasicType(eBasicTypeVoid).GetPointerType();
    }
    
    if (void_ptr_type.IsValid()) {
      // Create a Value and then a ValueObject for the object pointer
      Value temp_value;
      // Use correct ValueType for tagged vs regular pointers
      if (m_introspector_up && m_introspector_up->IsTaggedPointer(object_ptr)) {
        // Tagged pointers are immediate values, not memory addresses
        temp_value.SetValueType(Value::ValueType::Scalar);
        LLDB_LOG(log, "GNUstepObjCRuntime: Creating scalar ValueObject for tagged pointer 0x{0:x}", object_ptr);
      } else {
        // Regular object pointers are load addresses
        temp_value.SetValueType(Value::ValueType::LoadAddress);
        LLDB_LOG(log, "GNUstepObjCRuntime: Creating load address ValueObject for regular pointer 0x{0:x}", object_ptr);
      }
      temp_value.GetScalar() = object_ptr;
      temp_value.SetCompilerType(void_ptr_type);
      
      ValueObjectSP temp_valobj_sp = ValueObjectConstResult::Create(
          exe_ctx.GetBestExecutionContextScope(), temp_value, ConstString("temp_object"));
          
      if (temp_valobj_sp) {
        // Try our ID dispatcher formatter
        StreamString formatter_stream;
        TypeSummaryOptions summary_options;
        if (formatters::GNUstepUniversalSummaryProvider(*temp_valobj_sp, formatter_stream, summary_options)) {
          std::string formatter_output = formatter_stream.GetData();
          if (!formatter_output.empty() && formatter_output != "nil" && 
              formatter_output.find("GNUstep object at") == std::string::npos) {
            str.Printf("%s", formatter_output.c_str());
            LLDB_LOG(log, "GNUstepObjCRuntime: Using ID dispatcher fallback: {0}", formatter_output);
            return llvm::Error::success();
          }
        }
      }
    }
  }

  // Fallback: try to get class name using introspector  
  LLDB_LOG(log, "GNUstepObjCRuntime: Formatter fallback failed, trying introspector fallback");
  if (m_introspector_up) {
    LLDB_LOG(log, "GNUstepObjCRuntime: About to call GetClassName(0x{0:x})", object_ptr);
    class_name = m_introspector_up->GetClassName(object_ptr);
    LLDB_LOG(log, "GNUstepObjCRuntime: GetClassName returned: '{0}'", class_name);
    if (!class_name.empty()) {
      str.Printf("(%s *) 0x%" PRIx64, class_name.c_str(), object_ptr);
      LLDB_LOG(log, "GNUstepObjCRuntime: Using introspector class name fallback: {0}", class_name);
      return llvm::Error::success();
    }
  }

  // Final safe fallback - raw address
  str.Printf("GNUstep object at 0x%" PRIx64, object_ptr);
  LLDB_LOG(log, "GNUstepObjCRuntime: Using final raw address fallback");
  
  
  return llvm::Error::success();
}

bool GNUstepObjCRuntime::GetDynamicTypeAndAddress(ValueObject &in_value,
                                                  lldb::DynamicValueType use_dynamic,
                                                  TypeAndOrName &class_type_or_name,
                                                  Address &address,
                                                  Value::ValueType &value_type) {
  Log *log = GetLog(LLDBLog::Process | LLDBLog::Types);
  LLDB_LOG(log, "GNUstepObjCRuntime::GetDynamicTypeAndAddress called");
  
  // Add reentrancy guard to prevent recursive calls
  SimpleReentrancyGuard guard(m_in_dynamic_type_check);
  if (!guard.IsAcquired()) {
    LLDB_LOG(log, "GNUstepObjCRuntime: Reentrancy detected in GetDynamicTypeAndAddress, returning false");
    return false;
  }
  
  // Clear the result first
  class_type_or_name.Clear();
  value_type = Value::ValueType::Scalar;
  
  if (!m_introspector_up) {
    LLDB_LOG(log, "No introspector available");
    return false;
  }
  
  // Check if this could have a dynamic value
  if (!CouldHaveDynamicValue(in_value)) {
    LLDB_LOG(log, "Object could not have dynamic value");
    return false;
  }
  
  // Get the object address first to check for tagged pointers
  lldb::addr_t object_addr = in_value.GetPointerValue();
  LLDB_LOG(log, "GNUstepObjCRuntime: GetDynamicTypeAndAddress for object at 0x{0:x}", object_addr);
  if (object_addr == 0 || object_addr == LLDB_INVALID_ADDRESS) {
    LLDB_LOG(log, "Invalid object address");
    return false;
  }
  
  // Check if this is a tagged pointer - they need special handling
  std::string class_name;
  bool is_tagged = m_introspector_up->IsTaggedPointer(object_addr);
  LLDB_LOG(log, "GNUstepObjCRuntime: IsTaggedPointer(0x{0:x}) = {1}", object_addr, is_tagged);
  
  if (is_tagged) {
    // For tagged pointers, get the class name directly using runtime functions
    class_name = m_introspector_up->GetTaggedPointerClassName(object_addr);
    LLDB_LOG(log, "Tagged pointer detected, class: {0}", class_name);
  } else {
    // For regular objects, use normal ISA resolution
    LLDB_LOG(log, "GNUstepObjCRuntime: Calling GetClassNameFromObject for regular object");
    class_name = m_introspector_up->GetClassNameFromObject(in_value);
    LLDB_LOG(log, "GNUstepObjCRuntime: GetClassNameFromObject returned: '{0}'", class_name);
  }
  
  if (class_name.empty()) {
    LLDB_LOG(log, "Could not get class name from object");
    return false;
  }
  
  LLDB_LOG(log, "Got dynamic class name: {0}", class_name);
  
  // For tagged pointers, NEVER set LoadAddress - keep as Scalar
  // This prevents LLDB from trying to dereference tagged pointer values as memory addresses
  if (is_tagged) {
    // Tagged pointers are immediate values, not memory addresses
    value_type = Value::ValueType::Scalar;
    // Do NOT set an address - tagged pointers don't have backing memory
    // The object_addr itself IS the data (encoded)
    LLDB_LOG(log, "Tagged pointer - keeping as Scalar, no address set");
  } else {
    // Regular objects: provide load address for memory access
    address.SetRawAddress(object_addr);
    value_type = Value::ValueType::LoadAddress;
    LLDB_LOG(log, "Regular object - setting LoadAddress to 0x{0:x}", object_addr);
  }
  
  // Set the class name in the result
  class_type_or_name.SetName(ConstString(class_name));
  
  // Get CompilerType from DeclVendor to enable proper formatter dispatch
  // This is what was missing - LLDB needs CompilerType information to dispatch formatters
  // for synthetic children properly (like dictionary [0].key, [0].value)
  DeclVendor *decl_vendor = GetDeclVendor();
  if (decl_vendor) {
    LLDB_LOG(log, "GNUstepObjCRuntime: Looking up CompilerType for class: {0}", class_name);
    
    std::vector<CompilerDecl> decls;
    uint32_t found_decls = decl_vendor->FindDecls(ConstString(class_name), false, 1, decls);
    LLDB_LOG(log, "GNUstepObjCRuntime: DeclVendor FindDecls returned {0} declarations for {1}", 
             found_decls, class_name);
    
    if (found_decls > 0 && !decls.empty()) {
      // Get the CompilerType from the declaration
      CompilerType class_compiler_type = decls[0].GetType();
      LLDB_LOG(log, "GNUstepObjCRuntime: Got CompilerType from decl - IsValid: {0}", 
               class_compiler_type.IsValid());
      
      if (class_compiler_type.IsValid()) {
        // Make it a pointer type for ObjC objects
        CompilerType objc_pointer_type = class_compiler_type.GetPointerType();
        if (objc_pointer_type.IsValid()) {
          class_type_or_name.SetCompilerType(objc_pointer_type);
          LLDB_LOG(log, "GNUstepObjCRuntime: SUCCESSFULLY set CompilerType {0}* for class {1}", 
                   class_name, class_name);
        } else {
          LLDB_LOG(log, "GNUstepObjCRuntime: Failed to create pointer type for class {0}", class_name);
        }
      } else {
        LLDB_LOG(log, "GNUstepObjCRuntime: Invalid CompilerType returned for class {0}", class_name);
      }
    } else {
      LLDB_LOG(log, "GNUstepObjCRuntime: DeclVendor could not find class {0} (found_decls={1})", 
               class_name, found_decls);
    }
  } else {
    LLDB_LOG(log, "GNUstepObjCRuntime: No DeclVendor available for CompilerType lookup");
  }
  
  // Return true only if we have meaningful type information
  bool success = !class_type_or_name.IsEmpty();
  LLDB_LOG(log, "Dynamic type resolution: {0} at 0x{1:x} - success: {2}", 
           class_name, object_addr, success);
  return success;
}

TypeAndOrName GNUstepObjCRuntime::FixUpDynamicType(const TypeAndOrName &type_and_or_name,
                                                   ValueObject &static_value) {
  Log *log = GetLog(LLDBLog::Process | LLDBLog::Types);
  LLDB_LOG(log, "GNUstepObjCRuntime::FixUpDynamicType called");
  
  if (!m_introspector_up) {
    LLDB_LOG(log, "No introspector available for FixUpDynamicType");
    return type_and_or_name;
  }
  
  // If we already have a class name from dynamic typing, use it
  if (type_and_or_name.HasName()) {
    return type_and_or_name;
  }
  
  // Try to get the dynamic class name
  std::string class_name = m_introspector_up->GetClassNameFromObject(static_value);
  if (!class_name.empty()) {
    LLDB_LOG(log, "FixUpDynamicType resolved to: {0}", class_name);
    TypeAndOrName result(type_and_or_name);
    result.SetName(ConstString(class_name));
    return result;
  }
  
  return type_and_or_name;
}

bool GNUstepObjCRuntime::CouldHaveDynamicValue(ValueObject &in_value) {
  Log *log = GetLog(LLDBLog::Process | LLDBLog::Types);
  LLDB_LOG(log, "GNUstepObjCRuntime::CouldHaveDynamicValue called");
  
  // Check if this is a valid object pointer
  lldb::addr_t obj_addr = in_value.GetPointerValue();
  if (obj_addr == 0 || obj_addr == LLDB_INVALID_ADDRESS) {
    LLDB_LOG(log, "Invalid object address, no dynamic value possible");
    return false;
  }
  
  // Check the static type - should be an Objective-C object pointer
  CompilerType static_type = in_value.GetCompilerType();
  if (static_type.IsValid()) {
    // Check if it's a pointer type
    if (static_type.IsPointerType()) {
      CompilerType pointee_type = static_type.GetPointeeType();
      if (pointee_type.IsValid()) {
        // Check if it looks like an Objective-C class
        std::string type_name = pointee_type.GetTypeName().GetCString();
        if (type_name.find("NS") == 0 || type_name == "id" || type_name.find("objc_object") != std::string::npos) {
          LLDB_LOG(log, "Type {0} could have dynamic value", type_name);
          return true;
        }
      }
    }
  }
  
  // If we have an introspector, check if it's a valid object
  if (m_introspector_up) {
    bool is_valid = m_introspector_up->IsValidObjectPointer(obj_addr);
    LLDB_LOG(log, "Introspector validation: {0}", is_valid ? "valid" : "invalid");
    return is_valid;
  }
  
  // Conservative default: assume it could have dynamic value
  LLDB_LOG(log, "Assuming could have dynamic value (conservative default)");
  return true;
}

lldb::BreakpointResolverSP
GNUstepObjCRuntime::CreateExceptionResolver(const lldb::BreakpointSP &bkpt, 
                                           bool catch_bp, bool throw_bp) {
  // Stub implementation
  Log *log = GetLog(LLDBLog::Process | LLDBLog::Breakpoints);
  LLDB_LOG(log, "GNUstepObjCRuntime::CreateExceptionResolver called");
  return nullptr;
}

lldb::ThreadPlanSP GNUstepObjCRuntime::GetStepThroughTrampolinePlan(Thread &thread,
                                                                    bool stop_others) {
  Log *log = GetLog(LLDBLog::Step);
  LLDB_LOG(log, "GNUstepObjCRuntime::GetStepThroughTrampolinePlan called");
  
  // Get the current thread's stack frame
  StackFrameSP frame_sp = thread.GetStackFrameAtIndex(0);
  if (!frame_sp) {
    LLDB_LOG(log, "No current stack frame available");
    return nullptr;
  }
  
  // Get the symbol context for the current frame
  // Focus on symbols since objc_msgSend functions are typically runtime symbols
  SymbolContext sc = frame_sp->GetSymbolContext(eSymbolContextSymbol);
  
  // Check if we have a symbol
  const char *symbol_name = nullptr;
  if (sc.symbol && sc.symbol->GetName()) {
    symbol_name = sc.symbol->GetName().GetCString();
  }
  
  if (!symbol_name) {
    LLDB_LOG(log, "No symbol name available for current frame");
    return nullptr;
  }
  
  LLDB_LOG(log, "Current symbol: {0}", symbol_name);
  
  // Check if this is an objc_msgSend trampoline function
  // GNUstep uses similar naming to Apple for these functions, plus some GNUstep-specific variants
  bool is_objc_trampoline = false;
  
  // Check for standard objc_msgSend variants
  if (strncmp(symbol_name, "objc_msgSend", 12) == 0) {
    // Handle various objc_msgSend variants:
    // - objc_msgSend (basic message send)
    // - objc_msgSendSuper (super calls)
    // - objc_msgSend_stret (struct returns)
    // - objc_msgSendSuper_stret (super calls with struct returns)
    is_objc_trampoline = (strcmp(symbol_name, "objc_msgSend") == 0 ||
                         strcmp(symbol_name, "objc_msgSendSuper") == 0 ||
                         strcmp(symbol_name, "objc_msgSend_stret") == 0 ||
                         strcmp(symbol_name, "objc_msgSendSuper_stret") == 0 ||
                         strcmp(symbol_name, "objc_msgSend_fpret") == 0 ||
                         strcmp(symbol_name, "objc_msgSend_fp2ret") == 0);
  }
  
  // Check for GNUstep-specific trampoline symbols  
  if (!is_objc_trampoline) {
    // GNUstep may have different symbol names for trampolines
    is_objc_trampoline = (strstr(symbol_name, "objc_block_trampoline") != nullptr ||
                         strstr(symbol_name, "objc_trampoline") != nullptr ||
                         strstr(symbol_name, "objc_msgLookup") != nullptr ||
                         strstr(symbol_name, "__objc_msg") != nullptr ||
                         (strstr(symbol_name, "objc") != nullptr && 
                          (strstr(symbol_name, "trampoline") != nullptr || 
                           strstr(symbol_name, "dispatch") != nullptr ||
                           strstr(symbol_name, "lookup") != nullptr)));
  }
  
  if (!is_objc_trampoline) {
    LLDB_LOG(log, "Not in objc_msgSend trampoline, symbol: {0}", symbol_name);
    return nullptr;
  }
  
  // Verify this symbol is from the objc runtime library, not user code
  if (sc.module_sp) {
    const char *module_name = sc.module_sp->GetFileSpec().GetFilename().GetCString();
    if (module_name) {
      bool is_objc_runtime = (strstr(module_name, "libobjc") != nullptr ||
                             strstr(module_name, "libgnustep-base") != nullptr ||
                             strstr(module_name, "libs-base") != nullptr ||
                             strstr(module_name, "libobjc2") != nullptr);
      if (!is_objc_runtime) {
        LLDB_LOG(log, "Symbol {0} is not from objc runtime library (module: {1})", 
                 symbol_name, module_name);
        return nullptr;
      }
      LLDB_LOG(log, "Confirmed objc_msgSend trampoline in runtime library: {0}", module_name);
    }
  }
  
  LLDB_LOG(log, "Detected objc_msgSend trampoline: {0}, creating step-out plan", symbol_name);
  
  // Create a ThreadPlanStepOut to step out of the trampoline
  // This will cause LLDB to step over the objc_msgSend assembly and land
  // directly in the actual method implementation
  ThreadPlanSP step_out_plan_sp = std::make_shared<ThreadPlanStepOut>(
      thread,
      &sc,                    // symbol context
      false,                  // first_insn - not first instruction  
      stop_others,            // stop_others - as requested
      eVoteNoOpinion,         // report_stop_vote - no opinion
      eVoteNoOpinion,         // report_run_vote - no opinion
      0,                      // frame_idx - step out of current frame
      eLazyBoolCalculate,     // step_out_avoids_code_without_debug_info
      false,                  // continue_to_next_branch
      false                   // gather_return_value - not needed for trampolines
  );
  
  if (step_out_plan_sp) {
    LLDB_LOG(log, "Created ThreadPlanStepOut for objc_msgSend trampoline");
  } else {
    LLDB_LOG(log, "Failed to create ThreadPlanStepOut for objc_msgSend trampoline");
  }
  
  return step_out_plan_sp;
}

bool GNUstepObjCRuntime::IsModuleObjCLibrary(const lldb::ModuleSP &module_sp) {
  if (!module_sp)
    return false;
  
  const char *module_name = module_sp->GetFileSpec().GetFilename().GetCString();
  if (!module_name)
    return false;
  
  // Check for GNUstep runtime libraries - handle versioned library names
  // Examples: libobjc.so.4.6, libgnustep-base.so.1.31, libobjc2.so.4
  // Windows: gnustep-base-1_31.dll, libobjc-4.6.dll
  return (strstr(module_name, "libobjc.") ||           // libobjc.so.4.6 (note the dot)
          strstr(module_name, "libgnustep-base.") ||   // libgnustep-base.so.1.31  
          strstr(module_name, "libobjc2") ||           // libobjc2.so.4 or libobjc2
          strstr(module_name, "libBlocksRuntime") ||   // libBlocksRuntime for blocks support
          strstr(module_name, "gnustep-base-") ||      // Windows: gnustep-base-1_31.dll
          strstr(module_name, "libobjc-"));            // Windows: libobjc-4.6.dll
}

bool GNUstepObjCRuntime::ReadObjCLibrary(const lldb::ModuleSP &module_sp) {
  if (!IsModuleObjCLibrary(module_sp))
    return false;
  
  Log *log = GetLog(LLDBLog::Process | LLDBLog::Types);
  LLDB_LOG(log, "GNUstepObjCRuntime::ReadObjCLibrary called for module: {0}",
           module_sp->GetFileSpec().GetFilename().GetCString());
  
  m_has_read_objc_library = true;
  return true;
}

bool GNUstepObjCRuntime::HasReadObjCLibrary() {
  return m_has_read_objc_library;
}

bool GNUstepObjCRuntime::CalculateHasNewLiteralsAndIndexing() {
  if (!m_process) 
    return false;
    
  Log *log = GetLog(LLDBLog::Language);
  Target &target = m_process->GetTarget();
  
  // Check for subscripting method presence - this is the most reliable indicator
  SymbolContextList sc_list;
  
  // Primary check: NSDictionary subscripting (most reliable indicator)
  target.GetImages().FindSymbolsWithNameAndType(
      ConstString("-[NSDictionary objectForKeyedSubscript:]"),
      eSymbolTypeCode, sc_list);
  
  if (!sc_list.IsEmpty()) {
    LLDB_LOG(log, "GNUstep: Found NSDictionary subscripting support");
    return true;
  }
  
  // Fallback: NSArray subscripting
  sc_list.Clear();
  target.GetImages().FindSymbolsWithNameAndType(
      ConstString("-[NSArray objectAtIndexedSubscript:]"),
      eSymbolTypeCode, sc_list);
      
  if (!sc_list.IsEmpty()) {
    LLDB_LOG(log, "GNUstep: Found NSArray subscripting support");
    return true;
  }
  
  // Check for GNUstep Base version symbols as indicator
  sc_list.Clear();
  target.GetImages().FindSymbolsWithNameAndType(
      ConstString("gnustep_base_version"), 
      eSymbolTypeData, sc_list);
      
  if (!sc_list.IsEmpty()) {
    // Assume modern GNUstep Base has subscripting (Base 1.24+)
    LLDB_LOG(log, "GNUstep: Found gnustep_base_version, assuming subscripting support");
    return true;
  }
  
  // Check for NSConstantString class as fallback indicator
  sc_list.Clear(); 
  target.GetImages().FindSymbolsWithNameAndType(
      ConstString("NSConstantString"),
      eSymbolTypeObjCClass, sc_list);
      
  if (!sc_list.IsEmpty()) {
    // If we have NSConstantString, we likely have modern GNUstep Base
    LLDB_LOG(log, "GNUstep: Found NSConstantString class, likely modern GNUstep Base");
    return true;
  }
  
  LLDB_LOG(log, "GNUstep: No subscripting support detected");
  return false;
}

llvm::Expected<std::unique_ptr<UtilityFunction>>
GNUstepObjCRuntime::CreateObjectChecker(std::string name, ExecutionContext &exe_ctx) {
  Log *log = GetLog(LLDBLog::Process | LLDBLog::Types);
  LLDB_LOG(log, "GNUstepObjCRuntime::CreateObjectChecker called with name: {0}", name);
  
  // Generate the code for the object checker function
  // This function checks if an Objective-C object is valid and optionally
  // whether it responds to a given selector.
  // If the object is invalid or doesn't respond to the selector, it causes
  // a controlled crash by dereferencing a null pointer, which can be caught
  // by LLDB to handle conditional breakpoints.
  // The function signature is:
  // void <name>(void *obj, void *selector);
  // where 'obj' is the Objective-C object pointer and 'selector' is the SELectors.
  // If 'obj' is nil (0), it is considered valid. If 'selector' is nil (0),
  // the function only checks if 'obj' is valid.
  char check_function_code[2048];
  
  // Check if debugger-specific functions are available (Apple LLDB extensions)
  static const ConstString g_gdb_object_getClass("gdb_object_getClass");
  bool has_gdb_object_getClass = false;
  
  // Check for gdb_object_getClass symbol (LLDB-specific debugging function)
  if (Process *process = exe_ctx.GetProcessPtr()) {
    Target &target = process->GetTarget();
    const ModuleList &module_list = target.GetImages();
    for (size_t i = 0; i < module_list.GetSize(); ++i) {
      ModuleSP module_sp = module_list.GetModuleAtIndex(i);
      if (module_sp) {
        if (const Symbol *symbol = module_sp->FindFirstSymbolWithNameAndType(
                g_gdb_object_getClass, lldb::eSymbolTypeCode)) {
          if (symbol->ValueIsAddress() || symbol->GetAddressRef().IsValid()) {
            has_gdb_object_getClass = true;
            break;
          }
        }
      }
    }
  }
  
  int len;
  if (has_gdb_object_getClass) {
    // Use Apple's gdb_object_getClass approach if available
    len = ::snprintf(check_function_code, sizeof(check_function_code), R"(
extern "C" void *gdb_object_getClass(void *);
extern "C" int printf(const char *format, ...);

extern "C" void
%s(void *$__lldb_arg_obj, void *$__lldb_arg_selector) {
  // nil object is always OK for Objective-C
  if ($__lldb_arg_obj == (void *)0)
    return;
  
  // Check if object has a valid class using gdb_object_getClass (LLDB-specific function)
  if (!gdb_object_getClass($__lldb_arg_obj)) {
    // Invalid object - cause controlled crash for conditional breakpoints
    *((volatile int *)0) = 'ocgc';
  } else if ($__lldb_arg_selector != (void *)0) {
    // Use Objective-C respondsToSelector: syntax
    signed char $responds = (signed char)
        [(id)$__lldb_arg_obj respondsToSelector:
            (void *) $__lldb_arg_selector];
    if ($responds == (signed char) 0) {
      // Object doesn't respond to selector - cause controlled crash
      *((volatile int *)0) = 'ocgc';
    }
  }
})",
                     name.c_str());
  } else {
    // Fallback for GNUstep: simpler object checker without debugger-specific functions
    // Just validate that respondsToSelector works without class validation
    len = ::snprintf(check_function_code, sizeof(check_function_code), R"(
extern "C" int printf(const char *format, ...);

extern "C" void
%s(void *$__lldb_arg_obj, void *$__lldb_arg_selector) {
  // nil object is always OK for Objective-C
  if ($__lldb_arg_obj == (void *)0)
    return;
  
  // For GNUstep, skip complex object validation and just check selector response
  // This avoids linkage issues with debugger-specific functions
  if ($__lldb_arg_selector != (void *)0) {
    // Use Objective-C respondsToSelector: syntax - let runtime handle validation
    signed char $responds = (signed char)
        [(id)$__lldb_arg_obj respondsToSelector:
            (void *) $__lldb_arg_selector];
    if ($responds == (signed char) 0) {
      // Object doesn't respond to selector - cause controlled crash
      *((volatile int *)0) = 'ocgc';
    }
  }
  // If we get here, validation passed - continue normally
})",
                     name.c_str());
  }

  if (len >= (int)sizeof(check_function_code)) {
    LLDB_LOG(log, "GNUstepObjCRuntime::CreateObjectChecker: Generated code too long");
    return llvm::createStringError(llvm::inconvertibleErrorCode(), 
                                   "Object checker code generation failed - code too long");
  }

  LLDB_LOG(log, "GNUstepObjCRuntime::CreateObjectChecker: Generated object checker (gdb_object_getClass available: {0}):\n{1}", 
           has_gdb_object_getClass, check_function_code);

  // Create the utility function that LLDB can execute
  return GetTargetRef().CreateUtilityFunction(check_function_code, name,
                                              eLanguageTypeC, exe_ctx);
}

llvm::Expected<std::unique_ptr<UtilityFunction>>
GNUstepObjCRuntime::CreateSubscriptUtilityFunctions(ExecutionContext &exe_ctx) {
  Log *log = GetLog(LLDBLog::Process | LLDBLog::Types);
  LLDB_LOG(log, "GNUstepObjCRuntime::CreateSubscriptUtilityFunctions called");
  
  // Create utility functions that implement modern subscript syntax by forwarding to older methods
  // This enables po fruits[0] and po dict[@"key"] to work by translating to [fruits objectAtIndex:0]
  const char *subscript_functions = R"(
extern "C" void *objc_lookup_class(const char *);
extern "C" void *class_getMethodImplementation(void *cls, void *sel);
extern "C" void *sel_getUid(const char *);
extern "C" void *objc_msgSend(void *self, void *sel, ...);

// Implement objectAtIndexedSubscript: by calling objectAtIndex:
extern "C" void* 
__lldb_objc_objectAtIndexedSubscript(void *self, void *_cmd, long idx) {
  if (!self) return (void *)0;
  
  // Get the selector for objectAtIndex:
  void *sel_objectAtIndex = sel_getUid("objectAtIndex:");
  if (!sel_objectAtIndex) return (void *)0;
  
  // Forward the call to the older objectAtIndex: method
  return objc_msgSend(self, sel_objectAtIndex, idx);
}

// Implement objectForKeyedSubscript: by calling objectForKey:
extern "C" void*
__lldb_objc_objectForKeyedSubscript(void *self, void *_cmd, void *key) {
  if (!self) return (void *)0;
  
  // Get the selector for objectForKey:
  void *sel_objectForKey = sel_getUid("objectForKey:");
  if (!sel_objectForKey) return (void *)0;
  
  // Forward the call to the older objectForKey: method
  return objc_msgSend(self, sel_objectForKey, key);
}

// Entry point function for the utility
void __lldb_objc_subscript_utilities() {
  // This function exists only to satisfy the utility function loader
  // The actual work is done by the functions above
}
)";

  LLDB_LOG(log, "GNUstepObjCRuntime::CreateSubscriptUtilityFunctions: Generated subscript utility functions");

  // Create the utility function that LLDB can execute
  return GetTargetRef().CreateUtilityFunction(subscript_functions, "__lldb_objc_subscript_utilities",
                                              eLanguageTypeC, exe_ctx);
}

void GNUstepObjCRuntime::UpdateISAToDescriptorMapIfNeeded() {
  Log *log = GetLog(LLDBLog::Process | LLDBLog::Types);
  LLDB_LOG(log, "GNUstepObjCRuntime::UpdateISAToDescriptorMapIfNeeded called");
  
  // TODO: Re-implement using merged GNUstepObjCRuntimeIntrospector functionality
  // The old GNUstepRuntimeV2API and GNUstepClassDescriptor classes have been merged
  // into GNUstepObjCRuntimeIntrospector. This method will be restored once the
  // integration is complete.
  
  // Also update any custom classes we've encountered during runtime introspection
  if (m_introspector_up) {
    // The introspector may have cached ISA-to-name mappings we can use
    // This is a future enhancement point for custom class discovery
  }
}

ObjCLanguageRuntime::ClassDescriptorSP
GNUstepObjCRuntime::GetClassDescriptorFromISA(ObjCISA isa) {
  Log *log = GetLog(LLDBLog::Process | LLDBLog::Types);
  LLDB_LOG(log, "GNUstepObjCRuntime::GetClassDescriptorFromISA called with ISA {0:x}", isa);
  
  if (!isa)
    return ClassDescriptorSP();
  
  // First check the base class cache
  UpdateISAToDescriptorMap();
  ClassDescriptorSP descriptor_sp = ObjCLanguageRuntime::GetClassDescriptorFromISA(isa);
  if (descriptor_sp)
    return descriptor_sp;
  
  // Create a generic class descriptor for this ISA
  // TODO: Replace with proper GNUstepClassDescriptor once integrated
  descriptor_sp = ClassDescriptorSP();
  
  // Add to cache if valid
  if (descriptor_sp && descriptor_sp->IsValid()) {
    AddClass(isa, descriptor_sp);
    return descriptor_sp;
  }
  
  return ClassDescriptorSP();
}

ObjCLanguageRuntime::ClassDescriptorSP
GNUstepObjCRuntime::GetClassDescriptor(ValueObject &valobj) {
  Log *log = GetLog(LLDBLog::Process | LLDBLog::Types);
  LLDB_LOG(log, "GNUstepObjCRuntime::GetClassDescriptor called for ValueObject");
  
  // Handle base class case (like Apple's implementation)
  if (valobj.IsBaseClass()) {
    ValueObject *parent = valobj.GetParent();
    if (parent && parent != &valobj) {
      ClassDescriptorSP parent_descriptor_sp = GetClassDescriptor(*parent);
      if (parent_descriptor_sp)
        return parent_descriptor_sp->GetSuperclass();
    }
    return nullptr;
  }
  
  // Get the ISA pointer from the object
  addr_t isa_pointer = valobj.GetPointerValue();
  if (!isa_pointer)
    return ClassDescriptorSP();
  
  // Read the ISA from the object's first field
  ExecutionContext exe_ctx(valobj.GetExecutionContextRef());
  Process *process = exe_ctx.GetProcessPtr();
  if (!process)
    return ClassDescriptorSP();
  
  Status error;
  ObjCISA isa = process->ReadPointerFromMemory(isa_pointer, error);
  if (error.Fail())
    return ClassDescriptorSP();
  
  return GetClassDescriptorFromISA(isa);
}

ObjCLanguageRuntime::ClassDescriptorSP
GNUstepObjCRuntime::GetClassDescriptorFromClassName(ConstString class_name) {
  Log *log = GetLog(LLDBLog::Process | LLDBLog::Types);
  LLDB_LOG(log, "GNUstepObjCRuntime::GetClassDescriptorFromClassName called for class: {0}", class_name.GetCString());
  
  if (!class_name)
    return ClassDescriptorSP();
  
  // First check if it's already in the cache using base class method
  ClassDescriptorSP cached_descriptor = ObjCLanguageRuntime::GetClassDescriptorFromClassName(class_name);
  if (cached_descriptor) {
    LLDB_LOG(log, "Class '{0}' found in cache", class_name.GetCString());
    return cached_descriptor;
  }
  
  // Use our runtime function to get the class address
  lldb::addr_t class_addr = CallRuntimeFunction("objc_getClass", class_name.GetCString());
  if (class_addr == LLDB_INVALID_ADDRESS || class_addr == 0) {
    LLDB_LOG(log, "objc_getClass returned invalid address for class: {0}", class_name.GetCString());
    return ClassDescriptorSP();
  }
  
  LLDB_LOG(log, "objc_getClass resolved class '{0}' to address 0x{1:x}", class_name.GetCString(), class_addr);
  
  // Create a class descriptor from the ISA (class address)
  ClassDescriptorSP descriptor_sp = GetClassDescriptorFromISA(class_addr);
  if (descriptor_sp && descriptor_sp->IsValid()) {
    LLDB_LOG(log, "Successfully created class descriptor for '{0}'", class_name.GetCString());
    return descriptor_sp;
  }
  
  LLDB_LOG(log, "Failed to create valid class descriptor for '{0}'", class_name.GetCString());
  return ClassDescriptorSP();
}

void GNUstepObjCRuntime::InitializeRuntimeAPI() {
  Log *log = GetLog(LLDBLog::Process | LLDBLog::Types);
  LLDB_LOG(log, "GNUstepObjCRuntime::InitializeRuntimeAPI - Initializing runtime API");
  
  if (!m_process) {
    LLDB_LOG(log, "No process available for runtime API");
    return;
  }
  
  // Use the merged runtime introspector for Foundation class enumeration
  if (m_introspector_up) {
    LLDB_LOG(log, "Runtime introspector available for Foundation class detection");
    
    // Use the merged functionality to get Foundation classes
    auto foundation_classes = m_introspector_up->GetFoundationClassNames();
    LLDB_LOG(log, "Found {0} Foundation classes", foundation_classes.size());
    
    // Log first few Foundation classes for debugging
    size_t count = 0;
    for (const auto &cls : foundation_classes) {
      if (count++ < 10) {
        LLDB_LOG(log, "  Foundation class: {0}", cls);
      }
    }
    
    // Install subscript method mapping for GNUstep
    InstallSubscriptMethodMapping();
  } else {
    LLDB_LOG(log, "Runtime introspector not available, using fallback mechanisms");
  }
}

DeclVendor *GNUstepObjCRuntime::GetDeclVendor() {
  if (!m_decl_vendor_up) {
    Log *log = GetLog(LLDBLog::Process | LLDBLog::Types);
    // TODO: Re-implement DeclVendor functionality after cleanup
    // m_decl_vendor_up = std::make_unique<GNUstepObjCDeclVendor>(*this);
    LLDB_LOG(log, "DeclVendor temporarily disabled during refactoring");
  }
  
  return m_decl_vendor_up.get();
}

void GNUstepObjCRuntime::InstallSubscriptMethodMapping() {
  Log *log = GetLog(LLDBLog::Process | LLDBLog::Types);
  
  // Check if NSArray responds to objectAtIndex:
  // If it does, we can safely map subscript calls to traditional methods
  ExecutionContext exe_ctx(m_process);
  
  // Enhanced check using our runtime API for better reliability
  if (m_introspector_up) {
    // TODO: Re-implement using merged introspector functionality
    // bool array_supports_index = m_introspector_up->ClassRespondsToSelector("NSArray", "objectAtIndex:");
    // bool dict_supports_key = m_introspector_up->ClassRespondsToSelector("NSDictionary", "objectForKey:");
    bool array_supports_index = true; // Assume Foundation classes support standard methods
    bool dict_supports_key = true;
    
    if (array_supports_index && dict_supports_key) {
      LLDB_LOG(log, "GNUstep classes support traditional methods via runtime API, subscript mapping enabled");
      m_subscript_mapping_enabled = true;
      
      // Install expression evaluation hooks for modern subscript syntax
      InstallExpressionEvaluationHooks();
      
      return;
    } else {
      LLDB_LOG(log, "Runtime API check failed: NSArray->objectAtIndex: %s, NSDictionary->objectForKey: %s",
               array_supports_index ? "YES" : "NO", dict_supports_key ? "YES" : "NO");
    }
  }
  
  // Fallback to expression evaluation if runtime API is not available
  std::string check_expr = R"(
    (BOOL)[(Class)objc_getClass("NSArray") respondsToSelector:@selector(objectAtIndex:)] &&
    (BOOL)[(Class)objc_getClass("NSDictionary") respondsToSelector:@selector(objectForKey:)]
  )";
  
  EvaluateExpressionOptions options = MakeSafeExpressionOptions();
  
  ValueObjectSP result_sp;
  Status error;
  UserExpression::Evaluate(exe_ctx, options, check_expr.c_str(), 
                           "", result_sp, nullptr);
  
  if (error.Success() && result_sp && result_sp->GetValueAsUnsigned(0)) {
    LLDB_LOG(log, "GNUstep classes support traditional methods via expression evaluation, subscript mapping enabled");
    m_subscript_mapping_enabled = true;
    
    // Install expression evaluation hooks for modern subscript syntax
    InstallExpressionEvaluationHooks();
  } else {
    LLDB_LOG(log, "Could not verify GNUstep method support, subscript mapping disabled");
    m_subscript_mapping_enabled = false;
  }
}

void GNUstepObjCRuntime::InstallExpressionEvaluationHooks() {
  Log *log = GetLog(LLDBLog::Language | LLDBLog::Types);
  LLDB_LOG(log, "Installing expression evaluation hooks for GNUstep ObjC runtime");
  
  // Prevent multiple installations
  if (m_expression_hooks_installed) {
    LLDB_LOG(log, "Expression evaluation hooks already installed");
    return;
  }
  
  // 1) Resolve and cache canonical ObjC runtime symbols from libobjc2
  ResolveAndCacheRuntimeSymbols();
  
  // Early-out if we can't resolve ANY runtime symbols yet - be more conservative
  // Research Agent Plan: Only require minimal symbol availability for activation
  if (m_objc_msgSend_addr == LLDB_INVALID_ADDRESS &&
      m_objc_getClass_addr == LLDB_INVALID_ADDRESS &&
      m_sel_getUid_addr == LLDB_INVALID_ADDRESS) {
    LLDB_LOG(log, "No core runtime symbols available yet, deferring installation");
    return;
  }
  
  // 2) Ensure CFStringCreateWithBytes is available (real or fallback) 
  EnsureCFStringCreateWithBytes();
  
  // 3) Ensure array/dictionary literal support is available
  EnsureArrayDictionaryLiteralSupport();
  
  // 3) Inject runtime function prototypes and minimal Foundation interfaces into scratch AST
  // Research Agent Plan: Include eLanguageTypeC and make declarations unconditional
  Target &target = GetProcess()->GetTarget();
  for (LanguageType lang : {eLanguageTypeC, eLanguageTypeObjC, eLanguageTypeObjC_plus_plus}) {
    auto ts_or_err = target.GetScratchTypeSystemForLanguage(lang);
    if (ts_or_err) {
      auto ts_sp = *ts_or_err;
      if (ts_sp) {
        auto *ts = llvm::dyn_cast<TypeSystemClang>(ts_sp.get());
        if (ts) {
          LLDB_LOG(log, "Injecting runtime function prototypes into scratch AST for language: {0}", 
                   (lang == eLanguageTypeC) ? "C" : 
                   (lang == eLanguageTypeObjC) ? "ObjC" : "ObjC++");
          
          // Research Agent Plan: Unconditionally declare prototypes for comprehensive IR support
          InjectRuntimeFunctionDecls(*ts);
        }
      }
    }
  }
  
  // 4) Install subscript shims (safe no-op if symbols missing)
  ExecutionContext exe_ctx(GetProcess());
  CreateAndInstallSubscriptShims(exe_ctx);
  
  // 5) Install diagnostic utility function
  CreateDiagnosticUtility(exe_ctx);
  
  // 6) Register these symbols with IRForTarget for expression rewriting
  RegisterSymbolsWithIRForTarget();
  
  m_expression_hooks_installed = true;
  LLDB_LOG(log, "[GNUstep] Expression evaluation hooks installed successfully");
}

void GNUstepObjCRuntime::ResolveAndCacheRuntimeSymbols() {
  Log *log = GetLog(LLDBLog::Language | LLDBLog::Types);
  LLDB_LOG(log, "Resolving GNUstep runtime symbols for expression evaluation");
  
  Target &target = GetProcess()->GetTarget();
  const ModuleList &modules = target.GetImages();
  
  // Define the symbols we need for expression evaluation
  struct SymbolInfo {
    const char *name;
    const char *fallback_name;
    lldb::addr_t *cache_addr;
  };
  
  SymbolInfo symbols[] = {
    {"objc_msgSend", nullptr, &m_objc_msgSend_addr},
    {"objc_msgSend_stret", nullptr, &m_objc_msgSend_stret_addr},
    {"objc_msgSend_fpret", nullptr, &m_objc_msgSend_fpret_addr},
    {"objc_getClass", "objc_lookup_class", &m_objc_getClass_addr},
    {"sel_getUid", "sel_registerName", &m_sel_getUid_addr},
    {"object_getClass", nullptr, &m_object_getClass_addr},
    {"class_getMethodImplementation", nullptr, &m_class_getMethodImplementation_addr},
    {"class_addMethod", nullptr, &m_class_addMethod_addr},
    // Optional ARC helpers (non-fatal if not found)
    {"objc_retain", nullptr, &m_objc_retain_addr},
    {"objc_release", nullptr, &m_objc_release_addr},
    {"objc_autoreleaseReturnValue", nullptr, &m_objc_autoreleaseReturnValue_addr},
    {"objc_retainAutoreleasedReturnValue", nullptr, &m_objc_retainAutoreleasedReturnValue_addr},
    {nullptr, nullptr, nullptr}
  };
  
  // Search starting with GNUstep ObjC modules (libobjc-*.dll, libobjc2*)
  for (size_t i = 0; i < modules.GetSize(); ++i) {
    ModuleSP module_sp = modules.GetModuleAtIndex(i);
    if (!module_sp) continue;
    
    const char *module_name = module_sp->GetFileSpec().GetFilename().GetCString();
    if (!module_name) continue;
    
    // Check if this is a GNUstep ObjC runtime module
    bool is_objc_module = (strstr(module_name, "libobjc") ||
                          strstr(module_name, "objc2") ||
                          (strstr(module_name, "objc") && strstr(module_name, ".dll")));
    
    if (!is_objc_module) continue;
    
    LLDB_LOG(log, "Searching for runtime symbols in module: {0}", module_name);
    
    // Look for each symbol in this module
    for (int j = 0; symbols[j].name; j++) {
      if (*(symbols[j].cache_addr) != LLDB_INVALID_ADDRESS) continue; // Already found
      
      const Symbol *symbol = module_sp->FindFirstSymbolWithNameAndType(
          ConstString(symbols[j].name), eSymbolTypeCode);
      
      // Try fallback name if primary not found
      if (!symbol && symbols[j].fallback_name) {
        symbol = module_sp->FindFirstSymbolWithNameAndType(
            ConstString(symbols[j].fallback_name), eSymbolTypeCode);
      }
      
      if (symbol) {
        *(symbols[j].cache_addr) = symbol->GetLoadAddress(&target);
        LLDB_LOG(log, "Found {0} at 0x{1:x} in {2}", 
                symbols[j].name, *(symbols[j].cache_addr), module_name);
      }
    }
  }
  
  // Log what we found/didn't find
  int resolved_count = 0;
  for (int j = 0; symbols[j].name; j++) {
    if (*(symbols[j].cache_addr) != LLDB_INVALID_ADDRESS) {
      resolved_count++;
    } else {
      LLDB_LOG(log, "Warning: Could not resolve {0}", symbols[j].name);
    }
  }
  
  LLDB_LOG(log, "Resolved {0} out of {1} runtime symbols", resolved_count, 
           sizeof(symbols)/sizeof(symbols[0]) - 1);
}

void GNUstepObjCRuntime::EnsureCFStringCreateWithBytes() {
  Log *log = GetLog(LLDBLog::Language | LLDBLog::Types);
  LLDB_LOG(log, "Ensuring CFStringCreateWithBytes is available");
  
  if (m_cfstring_create_addr != LLDB_INVALID_ADDRESS) {
    LLDB_LOG(log, "CFStringCreateWithBytes already available at 0x{0:x}", m_cfstring_create_addr);
    return;
  }
  
  // Ensure we have execution context
  if (!m_process || !m_process->IsAlive()) {
    LLDB_LOG(log, "Process not available for CFStringCreateWithBytes installation");
    return;
  }
  
  Target &target = GetProcess()->GetTarget();
  const ModuleList &modules = target.GetImages();
  
  // First try to find the real CFStringCreateWithBytes in Foundation/CoreFoundation
  for (size_t i = 0; i < modules.GetSize(); ++i) {
    ModuleSP module_sp = modules.GetModuleAtIndex(i);
    if (!module_sp) continue;
    
    const char *module_name = module_sp->GetFileSpec().GetFilename().GetCString();
    if (!module_name) continue;
    
    // Check for Foundation/CoreFoundation modules
    bool is_foundation = (strstr(module_name, "gnustep-base") ||
                         strstr(module_name, "Foundation") ||
                         strstr(module_name, "CoreFoundation"));
    
    if (!is_foundation) continue;
    
    const Symbol *symbol = module_sp->FindFirstSymbolWithNameAndType(
        ConstString("CFStringCreateWithBytes"), eSymbolTypeCode);
    
    if (symbol) {
      m_cfstring_create_addr = symbol->GetLoadAddress(&target);
      LLDB_LOG(log, "Found real CFStringCreateWithBytes at 0x{0:x} in {1}", 
               m_cfstring_create_addr, module_name);
      return;
    }
  }

  // GNUstep doesn't have CFString, so we use a simple redirect to NSString
  // We'll use the address of objc_msgSend as a placeholder and handle the 
  // actual string creation in our expression evaluation
  if (m_objc_msgSend_addr != LLDB_INVALID_ADDRESS) {
    // Use a synthetic address that we'll recognize in our runtime
    // This is a hack but works around the utility function issues
    m_cfstring_create_addr = m_objc_msgSend_addr;
    LLDB_LOG(log, "Using objc_msgSend as CFStringCreateWithBytes placeholder at 0x{0:x}", 
             m_cfstring_create_addr);
  } else {
    LLDB_LOG(log, "Warning: Cannot provide CFStringCreateWithBytes fallback - objc_msgSend not available");
  }
}

void GNUstepObjCRuntime::EnsureArrayDictionaryLiteralSupport() {
  Log *log = GetLog(LLDBLog::Language | LLDBLog::Types);
  LLDB_LOG(log, "Ensuring array and dictionary literal support is available");
  
  // Skip if already set up
  if (m_array_literal_addr != LLDB_INVALID_ADDRESS && 
      m_dict_literal_addr != LLDB_INVALID_ADDRESS) {
    LLDB_LOG(log, "Array/Dictionary literal support already available");
    return;
  }
  
  Target &target = GetProcess()->GetTarget();
  ExecutionContext exe_ctx(GetProcess());
  
  // Enhanced safety checks to prevent hanging
  if (!exe_ctx.HasProcessScope() || !exe_ctx.GetProcessPtr()) {
    LLDB_LOG(log, "No valid execution context for array/dictionary literal installation");
    return;
  }
  
  Process *process = exe_ctx.GetProcessPtr();
  if (!process->IsAlive()) {
    LLDB_LOG(log, "Process not alive, skipping literal support installation");
    return;
  }
  
  // Don't install utility functions if we don't have basic runtime symbols yet
  if (m_objc_getClass_addr == LLDB_INVALID_ADDRESS || 
      m_objc_msgSend_addr == LLDB_INVALID_ADDRESS ||
      m_sel_getUid_addr == LLDB_INVALID_ADDRESS) {
    LLDB_LOG(log, "Basic runtime symbols not available, deferring literal support");
    return;
  }
  
  // Install NSArray arrayWithObjects:count: fallback
  if (m_array_literal_addr == LLDB_INVALID_ADDRESS) {
    LLDB_LOG(log, "Installing NSArray arrayWithObjects:count: fallback...");
    
    const char *array_literal_fallback = R"(
// GNUstep fallback for array literals: +[NSArray arrayWithObjects:count:]
void *objc_getClass(const char*);
void *sel_getUid(const char*);
void *objc_msgSend(void*, void*, ...);

void *NSArray_arrayWithObjects_count(void **objects, unsigned long count)
{
  void *nsarrayClass = objc_getClass("NSArray");
  if (!nsarrayClass) return (void*)0;
  
  void *sel = sel_getUid("arrayWithObjects:count:");
  if (!sel) return (void*)0;
  
  return objc_msgSend(nsarrayClass, sel, objects, count);
}
)";
    
    if (!m_array_literal_utility_fn) {
      auto utility_fn_or_err = target.CreateUtilityFunction(
          array_literal_fallback, "NSArray_arrayWithObjects_count", eLanguageTypeC, exe_ctx);
      
      if (!utility_fn_or_err) {
        LLDB_LOG(log, "Failed to create NSArray literal fallback: {0}", 
                 llvm::toString(utility_fn_or_err.takeError()));
      } else {
        m_array_literal_utility_fn = std::move(*utility_fn_or_err);
        LLDB_LOG(log, "NSArray literal utility function created successfully");
        
        // Install it
        DiagnosticManager diagnostic_manager;
        bool installation_succeeded = m_array_literal_utility_fn->Install(diagnostic_manager, exe_ctx);
        
        if (!installation_succeeded) {
          std::string diag_msg = diagnostic_manager.GetString();
          if (diag_msg.find("already installed") != std::string::npos) {
            installation_succeeded = true;
          }
        }
        
        if (installation_succeeded) {
          m_array_literal_addr = m_array_literal_utility_fn->StartAddress();
          LLDB_LOG(log, "NSArray literal fallback installed at 0x{0:x}", m_array_literal_addr);
        }
      }
    }
  }
  
  // Install NSDictionary dictionaryWithObjects:forKeys:count: fallback
  if (m_dict_literal_addr == LLDB_INVALID_ADDRESS) {
    LLDB_LOG(log, "Installing NSDictionary dictionaryWithObjects:forKeys:count: fallback...");
    
    const char *dict_literal_fallback = R"(
// GNUstep fallback for dictionary literals: +[NSDictionary dictionaryWithObjects:forKeys:count:]
void *objc_getClass(const char*);
void *sel_getUid(const char*);
void *objc_msgSend(void*, void*, ...);

void *NSDictionary_dictionaryWithObjects_forKeys_count(void **objects, void **keys, unsigned long count)
{
  void *nsdictClass = objc_getClass("NSDictionary");
  if (!nsdictClass) return (void*)0;
  
  void *sel = sel_getUid("dictionaryWithObjects:forKeys:count:");
  if (!sel) return (void*)0;
  
  return objc_msgSend(nsdictClass, sel, objects, keys, count);
}
)";
    
    if (!m_dict_literal_utility_fn) {
      auto utility_fn_or_err = target.CreateUtilityFunction(
          dict_literal_fallback, "NSDictionary_dictionaryWithObjects_forKeys_count", eLanguageTypeC, exe_ctx);
      
      if (!utility_fn_or_err) {
        LLDB_LOG(log, "Failed to create NSDictionary literal fallback: {0}", 
                 llvm::toString(utility_fn_or_err.takeError()));
      } else {
        m_dict_literal_utility_fn = std::move(*utility_fn_or_err);
        LLDB_LOG(log, "NSDictionary literal utility function created successfully");
        
        // Install it
        DiagnosticManager diagnostic_manager;
        bool installation_succeeded = m_dict_literal_utility_fn->Install(diagnostic_manager, exe_ctx);
        
        if (!installation_succeeded) {
          std::string diag_msg = diagnostic_manager.GetString();
          if (diag_msg.find("already installed") != std::string::npos) {
            installation_succeeded = true;
          }
        }
        
        if (installation_succeeded) {
          m_dict_literal_addr = m_dict_literal_utility_fn->StartAddress();
          LLDB_LOG(log, "NSDictionary literal fallback installed at 0x{0:x}", m_dict_literal_addr);
        }
      }
    }
  }
}

void GNUstepObjCRuntime::CreateAndInstallSubscriptShims(ExecutionContext &exe_ctx) {
  if (m_subscripts_installed)
    return;

  Log *log = GetLog(LLDBLog::Language | LLDBLog::Types);
  LLDB_LOG(log, "Installing subscript shims for modern Objective-C syntax");

  // 0) Require the basic runtime symbols to be resolvable when the UtilityFunction compiles
  if (m_class_addMethod_addr == LLDB_INVALID_ADDRESS ||
      m_objc_getClass_addr    == LLDB_INVALID_ADDRESS ||
      m_sel_getUid_addr       == LLDB_INVALID_ADDRESS) {
    // Try to (re)locate them if not already set
    ResolveAndCacheRuntimeSymbols(); // existing scan that sets the *_addr fields
  }
  if (m_class_addMethod_addr == LLDB_INVALID_ADDRESS ||
      m_objc_getClass_addr    == LLDB_INVALID_ADDRESS ||
      m_sel_getUid_addr       == LLDB_INVALID_ADDRESS) {
    LLDB_LOG(log, "subscript shims: required symbols missing; skipping install");
    return;
  }

  // 1) Build the utility function source - using pure C to avoid needing ObjC method declarations
  static const char *kSubscriptUtilsText = R"UTIL(
extern "C" void *objc_getClass(const char *name);
extern "C" void *sel_getUid(const char *name);
extern "C" void *objc_msgSend(void *self, void *sel, ...);
typedef void* (*IMP)(void*, void*, ...);
extern "C" int class_addMethod(void *cls, void *sel, void *imp, const char *types);

void* __lldb_objc_objectAtIndexedSubscript(void* self, void* _cmd, unsigned long long idx) {
    if (!self) return (void*)0;
    void* sel_objectAtIndex = sel_getUid("objectAtIndex:");
    if (!sel_objectAtIndex) return (void*)0;
    return objc_msgSend(self, sel_objectAtIndex, idx);
}

void* __lldb_objc_objectForKeyedSubscript(void* self, void* _cmd, void* key) {
    if (!self) return (void*)0;
    void* sel_objectForKey = sel_getUid("objectForKey:");
    if (!sel_objectForKey) return (void*)0;
    return objc_msgSend(self, sel_objectForKey, key);
}

int __lldb_install_subscript_shims(void *imp_array, void *imp_dict) {
    void *NSArray = objc_getClass("NSArray");
    void *NSDictionary = objc_getClass("NSDictionary");
    void *sel_array = sel_getUid("objectAtIndexedSubscript:");
    void *sel_dict  = sel_getUid("objectForKeyedSubscript:");
    int ok1 = class_addMethod(NSArray,     sel_array, (void*)imp_array, "@@:Q");
    int ok2 = class_addMethod(NSDictionary, sel_dict,  (void*)imp_dict,  "@@:@");
    return (ok1 || ok2) ? 1 : 1;
}

// Entry point function for the utility
void __lldb_subscript_utils() {
    // This function exists only to satisfy the utility function loader
    // The actual work is done by the functions above
}
)UTIL";

  if (!m_subscript_utils_fn) {
    Target &target = GetProcess()->GetTarget();
    auto uf_or_err = target.CreateUtilityFunction(
        kSubscriptUtilsText, /* name hint */ "__lldb_subscript_utils",
        eLanguageTypeC, exe_ctx);
    if (!uf_or_err) {
      LLDB_LOG(log, "failed to create subscript utils UF: {0}",
               llvm::toString(uf_or_err.takeError()));
      return;
    }
    m_subscript_utils_fn = std::move(*uf_or_err);
  }

  DiagnosticManager diagnostic_manager;
  if (!m_subscript_utils_fn->Install(diagnostic_manager, exe_ctx)) {
    LLDB_LOG(log, "failed to install subscript utils UF: {0}",
              diagnostic_manager.GetString());
    return;
  }

  // 2) Get addresses of the three functions we just injected
  auto get_sym_addr = [&](const char *name) -> addr_t {
    ConstString cs(name);
    // UtilityFunction publishes its symbols to the target; use the runtime resolver
    return LookupRuntimeSymbol(cs);
  };

  m_imp_array_subscript_addr = get_sym_addr("__lldb_objc_objectAtIndexedSubscript");
  m_imp_dict_subscript_addr  = get_sym_addr("__lldb_objc_objectForKeyedSubscript");
  m_install_subscripts_addr  = get_sym_addr("__lldb_install_subscript_shims");

  if (m_imp_array_subscript_addr == LLDB_INVALID_ADDRESS ||
      m_imp_dict_subscript_addr  == LLDB_INVALID_ADDRESS ||
      m_install_subscripts_addr  == LLDB_INVALID_ADDRESS) {
    LLDB_LOG(log, "could not resolve subscript utils addresses");
    return;
  }

  // 3) Call the installer exactly once, passing the two IMPs
  // Drive a tiny expression (now that symbol lookup works).
  {
    StreamString call;
    call.Printf("(int)__lldb_install_subscript_shims((void*)0x%llx,(void*)0x%llx)",
                (unsigned long long)m_imp_array_subscript_addr,
                (unsigned long long)m_imp_dict_subscript_addr);

    EvaluateExpressionOptions opts;
    opts.SetIgnoreBreakpoints(true);
    opts.SetUnwindOnError(true);
    opts.SetTryAllThreads(false);
    opts.SetLanguage(eLanguageTypeObjC);

    ValueObjectSP result;
    Target &target = GetProcess()->GetTarget();
    target.EvaluateExpression(call.GetString(), exe_ctx.GetFramePtr(), result, opts);

    // Best-effort: even if evaluation didn't return a VO, we proceed.
  }

  m_subscripts_installed = true;
  LLDB_LOG(log, "subscript shims installed");
}

void GNUstepObjCRuntime::CreateDiagnosticUtility(ExecutionContext &exe_ctx) {
  Log *log = GetLog(LLDBLog::Language | LLDBLog::Types);
  LLDB_LOG(log, "Installing diagnostic utility for GNUstep runtime state");

  if (m_diagnostic_utility_fn) {
    return; // Already installed
  }

  // Create diagnostic function that returns bitmask of what's working
  static const char *kDiagnosticUtilsText = R"UTIL(
extern "C" int __lldb_gnustep_diagnostic(void) {
    int result = 0;
    // bit 0: core symbols resolved (objc_msgSend, objc_getClass, sel_getUid)
    // bit 1: decls injected (this function exists = decls were injected)  
    // bit 2: CFString address ready
    // bit 3: subscript shims installed
    // bit 4: ARC helpers available
    
    result |= 1; // If this function runs, decls were injected
    
    // We can't easily check the other states from within the utility function
    // The caller can inspect individual symbol addresses if needed
    return result;
}
)UTIL";

  Target &target = GetProcess()->GetTarget();
  auto uf_or_err = target.CreateUtilityFunction(
      kDiagnosticUtilsText, "__lldb_gnustep_diagnostic",
      eLanguageTypeC, exe_ctx);
  if (!uf_or_err) {
    LLDB_LOG(log, "failed to create diagnostic utils UF: {0}",
             llvm::toString(uf_or_err.takeError()));
    return;
  }
  m_diagnostic_utility_fn = std::move(*uf_or_err);

  DiagnosticManager diagnostic_manager;
  if (!m_diagnostic_utility_fn->Install(diagnostic_manager, exe_ctx)) {
    LLDB_LOG(log, "failed to install diagnostic utils UF: {0}",
              diagnostic_manager.GetString());
    return;
  }

  // Get the address by finding the function in the target's symbol table
  SymbolContextList sc_list;
  target.GetImages().FindSymbolsWithNameAndType(
      ConstString("__lldb_gnustep_diagnostic"), eSymbolTypeCode, sc_list);
  
  if (sc_list.GetSize() > 0) {
    SymbolContext sc;
    sc_list.GetContextAtIndex(0, sc);
    if (sc.symbol) {
      m_diagnostic_function_addr = sc.symbol->GetLoadAddress(&target);
      LLDB_LOG(log, "Installed diagnostic utility at 0x{0:x}", m_diagnostic_function_addr);
    }
  }
}

// Helper function to create extern "C" function declarations
static clang::FunctionDecl *
CreateExternCFunction(TypeSystemClang &ts,
                      clang::DeclContext *dc,
                      llvm::StringRef name,
                      clang::QualType result_qt,
                      llvm::ArrayRef<clang::QualType> param_qts,
                      bool is_variadic) {
  clang::ASTContext &ast = ts.getASTContext();
  clang::IdentifierInfo &ii = ast.Idents.get(name);
  
  clang::FunctionProtoType::ExtProtoInfo epi;
  epi.Variadic = is_variadic;
  clang::QualType fn_ty = ast.getFunctionType(result_qt, param_qts, epi);
  
  auto *fd = clang::FunctionDecl::Create(ast, dc,
              clang::SourceLocation(), clang::SourceLocation(),
              &ii, fn_ty, /*TInfo*/nullptr,
              clang::SC_Extern);
  fd->setImplicit(true);
  dc->addDecl(fd);
  return fd;
}

void GNUstepObjCRuntime::InjectRuntimeFunctionDecls(TypeSystemClang &ts) {
  Log *log = GetLog(LLDBLog::Language | LLDBLog::Types);
  LLDB_LOG(log, "[GNUstep] Injecting runtime function prototypes into scratch AST");
  
  clang::ASTContext &ast = ts.getASTContext();
  clang::DeclContext *tu = ast.getTranslationUnitDecl();

  // --- typedefs: id, Class, SEL, IMP (all as void*)
  clang::QualType void_ty = ast.VoidTy;
  clang::QualType void_ptr = ast.getPointerType(void_ty);

  auto make_typedef = [&](llvm::StringRef name, clang::QualType qt) {
    clang::IdentifierInfo &ii = ast.Idents.get(name);
    auto *td = clang::TypedefDecl::Create(ast, tu,
                  clang::SourceLocation(), clang::SourceLocation(),
                  &ii, ast.getTrivialTypeSourceInfo(qt));
    tu->addDecl(td);
    return ast.getTypedefType(td);
  };
  
  clang::QualType qt_id    = make_typedef("id", void_ptr);
  clang::QualType qt_Class = make_typedef("Class", void_ptr);
  clang::QualType qt_SEL   = make_typedef("SEL", void_ptr);
  clang::QualType qt_IMP   = make_typedef("IMP", void_ptr);

  clang::QualType qt_char   = ast.CharTy;
  clang::QualType qt_ccharp = ast.getPointerType(ast.getConstType(qt_char));
  clang::QualType qt_bool   = ast.BoolTy;

  // id objc_msgSend(id, SEL, ...);
  {
    clang::QualType params[] = { qt_id, qt_SEL };
    CreateExternCFunction(ts, tu, "objc_msgSend", qt_id, params, /*variadic=*/true);
  }

  // Optional companions:
  // void objc_msgSend_stret(void*, id, SEL, ...);
  {
    clang::QualType params[] = { void_ptr, qt_id, qt_SEL };
    CreateExternCFunction(ts, tu, "objc_msgSend_stret", void_ty, params, /*variadic=*/true);
  }
  // double objc_msgSend_fpret(id, SEL, ...);
  {
    clang::QualType params[] = { qt_id, qt_SEL };
    CreateExternCFunction(ts, tu, "objc_msgSend_fpret", ast.DoubleTy, params, /*variadic=*/true);
  }

  // Class objc_getClass(const char *);
  {
    clang::QualType params[] = { qt_ccharp };
    CreateExternCFunction(ts, tu, "objc_getClass", qt_Class, params, /*variadic=*/false);
  }
  // Class objc_lookup_class(const char *);
  {
    clang::QualType params[] = { qt_ccharp };
    CreateExternCFunction(ts, tu, "objc_lookup_class", qt_Class, params, /*variadic=*/false);
  }

  // SEL sel_getUid(const char *);
  {
    clang::QualType params[] = { qt_ccharp };
    CreateExternCFunction(ts, tu, "sel_getUid", qt_SEL, params, /*variadic=*/false);
  }
  // SEL sel_registerName(const char *);
  {
    clang::QualType params[] = { qt_ccharp };
    CreateExternCFunction(ts, tu, "sel_registerName", qt_SEL, params, /*variadic=*/false);
  }

  // id object_getClass(id);
  {
    clang::QualType params[] = { qt_id };
    CreateExternCFunction(ts, tu, "object_getClass", qt_id, params, /*variadic=*/false);
  }

  // IMP class_getMethodImplementation(Class, SEL);
  {
    clang::QualType params[] = { qt_Class, qt_SEL };
    CreateExternCFunction(ts, tu, "class_getMethodImplementation", qt_IMP, params, /*variadic=*/false);
  }

  // bool class_addMethod(Class, SEL, IMP, const char *);
  {
    clang::QualType params[] = { qt_Class, qt_SEL, qt_IMP, qt_ccharp };
    CreateExternCFunction(ts, tu, "class_addMethod", qt_bool, params, /*variadic=*/false);
  }

  // ARC helpers (declare even if they map to 0 at runtime)
  {
    clang::QualType params1[] = { qt_id };
    CreateExternCFunction(ts, tu, "objc_retain", qt_id, params1, false);
    CreateExternCFunction(ts, tu, "objc_release", void_ty, params1, false);
    CreateExternCFunction(ts, tu, "objc_autoreleaseReturnValue", qt_id, params1, false);
    CreateExternCFunction(ts, tu, "objc_retainAutoreleasedReturnValue", qt_id, params1, false);
  }

  // And declare CFStringCreateWithBytes so the IR rewriter can always see a prototype:
  {
    // CF types are pointers here; signature aligned with what IRForTarget expects.
    clang::QualType params[] = { void_ptr, /*alloc*/
                                 ast.getPointerType(ast.UnsignedCharTy), /*bytes*/
                                 ast.LongTy, /*numBytes*/
                                 ast.IntTy,  /*encoding*/
                                 qt_bool     /*isExternalRep*/ };
    CreateExternCFunction(ts, tu, "CFStringCreateWithBytes", void_ptr, params, /*variadic=*/false);
  }

  // Add diagnostic utility function for field testing
  {
    // int __lldb_gnustep_diagnostic(void) - returns bitmask of what's installed
    CreateExternCFunction(ts, tu, "__lldb_gnustep_diagnostic", ast.IntTy, {}, /*variadic=*/false);
  }
  
  LLDB_LOG(log, "[GNUstep] Runtime function prototypes injected successfully");
}

void GNUstepObjCRuntime::RegisterSymbolsWithIRForTarget() {
  Log *log = GetLog(LLDBLog::Language | LLDBLog::Types);
  LLDB_LOG(log, "Registering runtime symbols with IRForTarget");
  
  // This is where we would hook into LLDB's IRForTarget to provide
  // symbol addresses for expression rewriting. For now, we cache the
  // addresses so they can be accessed by the expression evaluation system.
  
  // The actual registration happens through LLDB's expression system
  // when GetObjCRuntimeAddresses() is called during IR generation
  
  LLDB_LOG(log, "Runtime symbol registration completed");
}

std::map<std::string, lldb::addr_t> GNUstepObjCRuntime::GetObjCRuntimeAddresses() {
  std::map<std::string, lldb::addr_t> addresses;
  
  // Provide the symbol addresses we resolved for IR rewriting
  if (m_objc_msgSend_addr != LLDB_INVALID_ADDRESS)
    addresses["objc_msgSend"] = m_objc_msgSend_addr;
  if (m_objc_msgSend_stret_addr != LLDB_INVALID_ADDRESS)
    addresses["objc_msgSend_stret"] = m_objc_msgSend_stret_addr;
  if (m_objc_msgSend_fpret_addr != LLDB_INVALID_ADDRESS)
    addresses["objc_msgSend_fpret"] = m_objc_msgSend_fpret_addr;
  if (m_objc_getClass_addr != LLDB_INVALID_ADDRESS)
    addresses["objc_getClass"] = m_objc_getClass_addr;
  if (m_sel_getUid_addr != LLDB_INVALID_ADDRESS)
    addresses["sel_getUid"] = m_sel_getUid_addr;
  if (m_object_getClass_addr != LLDB_INVALID_ADDRESS)
    addresses["object_getClass"] = m_object_getClass_addr;
  if (m_class_getMethodImplementation_addr != LLDB_INVALID_ADDRESS)
    addresses["class_getMethodImplementation"] = m_class_getMethodImplementation_addr;
  if (m_cfstring_create_addr != LLDB_INVALID_ADDRESS)
    addresses["CFStringCreateWithBytes"] = m_cfstring_create_addr;
  if (m_class_addMethod_addr != LLDB_INVALID_ADDRESS)
    addresses["class_addMethod"] = m_class_addMethod_addr;
    
  // Optional ARC helpers
  if (m_objc_retain_addr != LLDB_INVALID_ADDRESS)
    addresses["objc_retain"] = m_objc_retain_addr;
  if (m_objc_release_addr != LLDB_INVALID_ADDRESS)
    addresses["objc_release"] = m_objc_release_addr;
  if (m_objc_autoreleaseReturnValue_addr != LLDB_INVALID_ADDRESS)
    addresses["objc_autoreleaseReturnValue"] = m_objc_autoreleaseReturnValue_addr;
  if (m_objc_retainAutoreleasedReturnValue_addr != LLDB_INVALID_ADDRESS)
    addresses["objc_retainAutoreleasedReturnValue"] = m_objc_retainAutoreleasedReturnValue_addr;
    
  return addresses;
}

lldb::addr_t GNUstepObjCRuntime::CallRuntimeFunction(const char *function_name, const char *string_arg) {
  if (!m_runtime_caller) {
    return LLDB_INVALID_ADDRESS;
  }

  // Delegate to the consolidated runtime function caller
  return m_runtime_caller->CallRuntimeFunction(function_name, string_arg);
}

lldb::addr_t GNUstepObjCRuntime::LookupRuntimeSymbol(ConstString name) {
  Log *log = GetLog(LLDBLog::Language | LLDBLog::Types);
  LLDB_LOG(log, "GNUstepObjCRuntime::LookupRuntimeSymbol called for: {0}", name.GetCString());
  
  // Prevent recursive installation when looking up symbols during hook installation
  static thread_local bool s_installing_hooks = false;
  
  // Make sure our symbol cache is ready (lazy installation)
  if (!m_expression_hooks_installed && !s_installing_hooks) {
    // Only install hooks if we have a stable execution context
    ExecutionContext exe_ctx(GetProcess());
    if (exe_ctx.HasProcessScope() && exe_ctx.GetProcessPtr()->IsAlive()) {
      s_installing_hooks = true;
      InstallExpressionEvaluationHooks();
      s_installing_hooks = false;
    } else {
      LLDB_LOG(log, "Deferring expression hooks installation - process not ready");
      // Don't try symbol resolution during hook installation to prevent recursion
      // Symbol resolution will happen naturally when hooks are installed later
    }
  }

  const llvm::StringRef s = name.GetStringRef();

  auto ret = [&](lldb::addr_t a) { 
    if (a != LLDB_INVALID_ADDRESS) {
      LLDB_LOG(log, "GNUstepObjCRuntime::LookupRuntimeSymbol returning 0x{0:x} for {1}", a, name.GetCString());
    } else {
      LLDB_LOG(log, "GNUstepObjCRuntime::LookupRuntimeSymbol returning INVALID_ADDRESS for {0}", name.GetCString());
    }
    return a == LLDB_INVALID_ADDRESS ? LLDB_INVALID_ADDRESS : a; 
  };

  // Handle class name resolution - this is called when IRForTarget needs to resolve
  // a class name like "NSArray" to the actual class object address
  if (m_objc_getClass_addr != LLDB_INVALID_ADDRESS) {
    // Check if this looks like a class name (starts with uppercase, contains typical class patterns)
    if (!s.empty() && (std::isupper(s[0]) || s.starts_with("NS") || s.starts_with("CF"))) {
      LLDB_LOG(log, "Attempting to resolve '{0}' as a class name using objc_getClass", s.str().c_str());
      
      // Call objc_getClass(class_name) to get the class object
      lldb::addr_t class_addr = CallRuntimeFunction("objc_getClass", s.str().c_str());
      if (class_addr != LLDB_INVALID_ADDRESS && class_addr != 0) {
        LLDB_LOG(log, "Successfully resolved class '{0}' to address 0x{1:x}", s.str().c_str(), class_addr);
        return ret(class_addr);
      }
    }
  }

  // Handle runtime function symbols
  if (s == "objc_msgSend")                 return ret(m_objc_msgSend_addr);
  if (s == "objc_msgSend_stret")           return ret(m_objc_msgSend_stret_addr);
  if (s == "objc_msgSend_fpret")           return ret(m_objc_msgSend_fpret_addr);
  if (s == "objc_getClass" || s == "objc_lookup_class")
                                                return ret(m_objc_getClass_addr);
  if (s == "sel_getUid" || s == "sel_registerName")
                                                return ret(m_sel_getUid_addr);
  if (s == "object_getClass")              return ret(m_object_getClass_addr);
  if (s == "class_getMethodImplementation")
                                                return ret(m_class_getMethodImplementation_addr);
  if (s == "class_addMethod")              return ret(m_class_addMethod_addr);

  // Optional ARC helpers (best effort)
  if (s == "objc_retain")                  return ret(m_objc_retain_addr);
  if (s == "objc_release")                 return ret(m_objc_release_addr);
  if (s == "objc_autoreleaseReturnValue")  return ret(m_objc_autoreleaseReturnValue_addr);
  if (s == "objc_retainAutoreleasedReturnValue") 
                                                return ret(m_objc_retainAutoreleasedReturnValue_addr);

  // NSString constant rewrite dependency:
  if (s == "CFStringCreateWithBytes") {
    // Ensure fallback is installed if the symbol didn't exist in Foundation/CoreFoundation
    LLDB_LOG(log, "[LookupRuntimeSymbol] CFStringCreateWithBytes requested, ensuring installation");
    EnsureCFStringCreateWithBytes();
    LLDB_LOG(log, "[LookupRuntimeSymbol] CFStringCreateWithBytes address: 0x{0:x}", m_cfstring_create_addr);
    return ret(m_cfstring_create_addr);
  }
  
  // GNUstep: Resolve __CFConstantStringClassReference to NSConstantString class
  if (s == "__CFConstantStringClassReference" || s == "_OBJC_CLASS_NSConstantString") {
    LLDB_LOG(log, "[LookupRuntimeSymbol] __CFConstantStringClassReference requested for GNUstep");
    
    // For GNUstep, this should point to the NSConstantString class object
    if (m_objc_getClass_addr != LLDB_INVALID_ADDRESS) {
      // We need to call objc_getClass("NSConstantString") to get the class pointer
      // For now, we'll use a cached value if available
      static lldb::addr_t nsConstantString_class = LLDB_INVALID_ADDRESS;
      
      if (nsConstantString_class == LLDB_INVALID_ADDRESS) {
        // Try to find it in the runtime
        Target &target = GetProcess()->GetTarget();
        const ModuleList &modules = target.GetImages();
        
        for (size_t i = 0; i < modules.GetSize(); ++i) {
          ModuleSP module_sp = modules.GetModuleAtIndex(i);
          if (!module_sp) continue;
          
          const Symbol *symbol = module_sp->FindFirstSymbolWithNameAndType(
              ConstString("_OBJC_CLASS_NSConstantString"), eSymbolTypeObjCClass);
          
          if (symbol) {
            nsConstantString_class = symbol->GetLoadAddress(&target);
            LLDB_LOG(log, "Found NSConstantString class at 0x{0:x}", nsConstantString_class);
            break;
          }
        }
        
        // If still not found, try to get it dynamically
        if (nsConstantString_class == LLDB_INVALID_ADDRESS) {
          // As a fallback, use NSString class which should work for constant strings
          const Symbol *nsstring_symbol = nullptr;
          for (size_t i = 0; i < modules.GetSize(); ++i) {
            ModuleSP module_sp = modules.GetModuleAtIndex(i);
            if (!module_sp) continue;
            
            nsstring_symbol = module_sp->FindFirstSymbolWithNameAndType(
                ConstString("_OBJC_CLASS_NSString"), eSymbolTypeObjCClass);
            
            if (nsstring_symbol) {
              nsConstantString_class = nsstring_symbol->GetLoadAddress(&target);
              LLDB_LOG(log, "Using NSString class as fallback at 0x{0:x}", nsConstantString_class);
              break;
            }
          }
        }
      }
      
      if (nsConstantString_class != LLDB_INVALID_ADDRESS) {
        LLDB_LOG(log, "Resolved __CFConstantStringClassReference to 0x{0:x}", nsConstantString_class);
        return ret(nsConstantString_class);
      }
    }
    
    LLDB_LOG(log, "Failed to resolve __CFConstantStringClassReference");
    return ret(LLDB_INVALID_ADDRESS);
  }

  // Handle C++ mangled names for basic runtime functions
  // LLDB's expression evaluator sometimes requests C++ mangled names instead of C names
  if (s == "_Z10sel_getUidPKc") {
    // This is the C++ mangled name for sel_getUid(const char*)
    return ret(m_sel_getUid_addr);
  }
  
  if (s == "_Z12objc_msgSendPvS_z") {
    // This is the C++ mangled name for objc_msgSend(void*, void*, ...)
    return ret(m_objc_msgSend_addr);
  }
  
  if (s == "_Z13objc_getClassPKc") {
    // This is the C++ mangled name for objc_getClass(const char*)
    return ret(m_objc_getClass_addr);
  }

  // Subscript shim functions (if installed):
  if (s == "__lldb_objc_objectAtIndexedSubscript")
                                                return ret(m_imp_array_subscript_addr);
  if (s == "__lldb_objc_objectForKeyedSubscript")
                                                return ret(m_imp_dict_subscript_addr);
  if (s == "__lldb_install_subscript_shims")
                                                return ret(m_install_subscripts_addr);

  // Diagnostic utility function:
  if (s == "__lldb_gnustep_diagnostic")
                                                return ret(m_diagnostic_function_addr);

  LLDB_LOG(log, "GNUstepObjCRuntime::LookupRuntimeSymbol: No match found for {0}", name.GetCString());
  return LLDB_INVALID_ADDRESS;
}

LLDB_PLUGIN_DEFINE(GNUstepObjCRuntime)
